# https://www.home-assistant.io/docs/blueprint/tutorial/
# https://www.home-assistant.io/docs/blueprint/
blueprint:
  name: Internet Extender Availability Notifications
  description: Send a notification when an extender is or was unavailable.
  domain: automation
  input:
    extender_entity_id:
      name: Extender Binary Sensor
      description: The binary sensor that knows the extender's availability.
      selector:
        entity:
          filter:
            domain:
              - binary_sensor
              - input_boolean
trigger:
  - platform: state
    entity_id: !input extender_entity_id
    # we need to this to prevent triggering on attribute changes
    to:
      - "on"
      - "off"
    for:
      minutes: 2
mode: queued
condition:
  - condition: state
    entity_id: binary_sensor.pieter_present
    state: "on"
  # - condition: time
  #   after: "06:00:00"
  #   before: "23:00:00"
action:
  # i added this because i think the real issue was that the original trigger also changed on attribute changes,
  # so it seemed like the "for" wasn't working, but keeping this here for future reference, since it's an
  # interesting pattern:
  # connectivity can sometimes be intermittent, which we expect
  # we're trying to catch a permanent outage
  # the underlying ping sensors run every 30 sec
  # so if it's still (or again) off at the 2 min mark, it's probably off for real
  # same for on
  # - delay:
  #     minutes: 2
  # - condition: template
  #   value_template: "{{ is_state(trigger.entity_id, trigger.to_state) }}"
  - service: notify.mobile_app_ceres
    data:
      title: "Internet"
      message: >-
        {% from 'datetime.jinja' import sec_to_hour_and_min %}
        {% set seconds = (as_timestamp(utcnow()) - as_timestamp(trigger.from_state.last_changed)) | int %}
        {% set duration = sec_to_hour_and_min(seconds) %}
        The {{ state_attr(trigger.entity_id, 'friendly_name') | lower }} {{ 'is unavailable' if trigger.to_state.state == 'off' else 'was unavailable for ' ~  duration }}.
      data:
        group: "home-internet"
        url: homeassistant://navigate/lovelace/internet
        tag: !input extender_entity_id
