- platform: template
  sensors:
    pieter_present:
      friendly_name: "Pieter Present"
      value_template: >-
        {{ is_state("input_boolean.pieter_present", "on") or
           is_state("person.pieter_rautenbach", "home") }}
    rouve_present:
      friendly_name: "Rouvé Present"
      value_template: >-
        {{ is_state("input_boolean.rouve_present", "on") or
           is_state("person.rouve_rautenbach", "home") }}
    contractor_mode:
      friendly_name: "Contractor Mode"
      value_template: >-
        {{ is_state("input_boolean.contractor_mode", "on") }}
    anybody_home:
      friendly_name: "Anybody Home"
      value_template: >-
        {{ is_state("input_boolean.pieter_present", "on") or is_state("input_boolean.rouve_present", "on") or
           is_state("input_boolean.guest_mode", "on") or is_state("input_boolean.contractor_mode", "on") }}
      icon_template: >-
        {% if is_state("input_boolean.pieter_present", "on") or is_state("input_boolean.rouve_present", "on") or
              is_state("input_boolean.guest_mode", "on") or is_state("input_boolean.contractor_mode", "on") %}
          mdi:home-account
        {% else %}
          mdi:home
        {% endif %}
    pieter_driving:
      friendly_name: "Pieter Driving"
      value_template: >-
        {{ is_state("input_boolean.pieter_driving", "on") }}
    electricity_feed:
      friendly_name: "Electricity"
      # https://www.home-assistant.io/integrations/binary_sensor/#device-class
      device_class: power
      value_template: >-
        {{ state_attr('sensor.home_assistant_server_battery', 'status') != 'Discharging' }}
      delay_off:
        minutes: 1
      # or must i use: {{ is_state('sensor.current_power', 'unavailable') }}
      icon_template: >-
        {% if states('sensor.current_power_2') is not none %}
          mdi:power-plug
        {% else %}
          mdi:power-plug-off
        {% endif %}
    internet_connection:
      friendly_name: "Internet"
      device_class: connectivity
      value_template: >-
        {{ is_state('binary_sensor.internet', 'on') }}
      icon_template: >-
        {% if is_state('binary_sensor.internet', 'on') %}
          mdi:server-network
        {% else %}
          mdi:server-network-off
        {% endif %}
    motion_detected:
      friendly_name: "Motion Detector"
      device_class: motion
      # motion_sensor_3 is the occupancy sensor and not the raw motion sensor and is delayed in the homebridge config by 5 sec
      value_template: >-
        {{ is_state('binary_sensor.motion_sensor_3', 'on') }}
      icon_template: >-
        {% if is_state('binary_sensor.motion_sensor_3', 'on') %}
          mdi:motion-sensor
        {% else %}
          mdi:walk
        {% endif %}
    no_recent_backup:
      friendly_name: "Recent Backup Problem"
      device_class: problem
      # get the last file, extract the date and compare
      value_template: >-
        {{ 'on' if ((states('sensor.last_backup') == 'unknown') or ((now() - states('sensor.last_backup')).days > 4)) else 'off' }}
      icon_template: >-
        {{ state_attr('sensor.last_backup', 'icon') }}

- platform: ping
  name: Internet
  host: www.google.com
  count: 5
  scan_interval: 180
