- platform: ffmpeg
  name: security_camera
  input: -rtsp_transport tcp -i rtsp://securitypi.local:8554/unicast
  # https://stackoverflow.com/questions/37427498/how-to-escape-double-and-single-quotes-in-yaml-within-the-same-string
  # https://stackoverflow.com/questions/6195872/applying-multiple-filters-at-once-with-ffmpeg
  # https://einar.slaskete.net/2011/09/05/adding-time-stamp-overlay-to-video-stream-using-ffmpeg/
  extra_arguments: >-
    -vf "hue=s=0, drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='%{localtime\:%Y-%m-%d %T}':fontcolor=white@0.8:x=10:y=10"
- platform: local_file
  name: security_camera_last_snapshot
  file_path: /home/homeassistant/.homeassistant/www/camera.security_camera_last.jpg
- platform: ffmpeg
  name: security_camera_last_clip
  input: /home/homeassistant/.homeassistant/www/camera.security_camera_last.mp4
