- platform: switch
  name: living_room_lamp
  entity_id: switch.living_room_lamp
- platform: switch
  name: front_door
  entity_id: switch.shelly1_77128c
- platform: switch
  name: backyard
  entity_id: switch.shelly1_b91f6f
- platform: switch
  name: garage
  entity_id: switch.shelly1_b95a0e
  name: Normal Light Group
  entities:
    - light.living_room_lamp
    - light.kitchen_counter
- platform: group
  name: Night Group
  entities:
    - light.foyer
    - light.kitchen_counter
