- platform: switch
  name: living_room_lamp
  entity_id: switch.living_room_lamp
- platform: switch
  name: front_door
  entity_id: switch.front_door
- platform: switch
  name: backyard
  entity_id: switch.backyard
- platform: switch
  name: garage
  entity_id: switch.garage
- platform: group
  name: Living Area Group
  entities:
    - light.foyer
    - light.dining_room
    - light.music_room
    - light.corner_lights
- platform: group
  name: Normal Light Group
  entities:
    - light.living_room_lamp
    - light.kitchen_counter
    - light.corner_lights
- platform: group
  name: Night Group
  entities:
    - light.foyer
    - light.kitchen_counter
    - light.hallway
- platform: group
  name: Yard Group
  entities:
    - light.front_door
    - light.backyard
- platform: group
  name: Inside Security Group
  entities:
    - light.foyer
    - light.living_room_lamp
- platform: group
  name: Main Bedroom Group
  entities:
    - light.pieter_bedside
    - light.rouve_bedside
- platform: group
  name: Corner Lights
  entities:
    - light.dining_room_corner_light
    - light.music_room_corner_light
