- platform: universal
  name: Living Room Universal
  children:
    - media_player.living_room
  commands:
    turn_on:
      service: script.entertainment_apple_tv_on
    turn_off:
      service: script.entertainment_off
    volume_up:
      service: script.hk_3380_vol_up
    volume_down:
      service: script.hk_3380_vol_down
    volume_mute:
      service: script.hk_3380_mute
- platform: shairport_sync
  name: Main Bedroom
  topic: shairport-sync/main-bedroom
- platform: universal
  name: Main Bedroom Universal
  children:
    - media_player.main_bedroom
  commands:
    turn_on:
      service: switch.turn_on
      target:
        entity_id: switch.tivoli_audio
    turn_off:
      service: switch.turn_off
      target:
        entity_id: switch.tivoli_audio
  attributes:
    state: switch.tivoli_audio
