sensor:
  - name: MQTT Broker Received Messages (1min load)
    state_topic: $SYS/broker/load/messages/received/1min
    unit_of_measurement: 'messages/s'
    icon: mdi:email-arrow-left-outline

  - name: MQTT Broker Sent Messages (1min load)
    state_topic: $SYS/broker/load/messages/sent/1min
    unit_of_measurement: 'messages/s'
    icon: mdi:email-arrow-right-outline
