title: Home
background: var(--background-image)
views:
  - !include ui-lovelace/main.yaml
  - !include ui-lovelace/entertainment.yaml
  - !include ui-lovelace/internet.yaml
  - !include ui-lovelace/security.yaml
  - !include ui-lovelace/gallery.yaml
  - !include ui-lovelace/floorplan.yaml
  - !include ui-lovelace/devices.yaml
  - !include ui-lovelace/test.yaml
button_card_templates:
  clock:
    variables:
      timezone: "Continent/City"
    show_name: true
    show_state: true
    show_icon: true
    show_label: true
    label: >
      [[[
        return (new Date()).toLocaleDateString("en-ZA", {timeZone: variables.timezone});
      ]]]
    icon: >
      [[[
        var hourNamesIndexed = ["twelve", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve"];
        var timeParts = (new Date()).toLocaleTimeString("en-ZA", {timeZone: variables.timezone, hour12: true}).split(':');
        var hour = parseInt(timeParts[0]);
        var minute = parseInt(timeParts[1]);
        return "mdi:clock-time-" + hourNamesIndexed[hour] + "-outline";
      ]]]
    color: var(--paper-item-icon-color)
    styles:
      grid:
        - grid-template-areas: '"n" "i" "s" "l"'
      name:
        - color: var(--secondary-text-color)
        - font-size: 1rem
      state:
        - color: var(--secondary-text-color)
        - font-size: 0.8rem
      label:
        - color: var(--secondary-text-color)
        - font-size: 0.8rem
    tap_action: none
