title: Home
background: var(--background-image)
views:
  - !include ui-lovelace/main.yaml
  - !include ui-lovelace/entertainment.yaml
  - !include ui-lovelace/internet.yaml
  - !include ui-lovelace/security.yaml
  - !include ui-lovelace/gallery.yaml
  - !include ui-lovelace/floorplan.yaml
  - !include ui-lovelace/devices.yaml
  - !include ui-lovelace/test.yaml
