title: Home
background: var(--background-image)
views:
  - !include ui-lovelace/main.yaml
  - !include ui-lovelace/environment.yaml
  - !include ui-lovelace/entertainment.yaml
  - !include ui-lovelace/internet.yaml
  - !include ui-lovelace/security.yaml
  - !include ui-lovelace/gallery.yaml
  # - !include ui-lovelace/floorplan.yaml
  - !include ui-lovelace/devices.yaml
  - !include ui-lovelace/test.yaml
button_card_templates:
  clock:
    variables:
      timezone: "Continent/City"
    show_name: true
    show_state: true
    show_icon: true
    show_label: true
    label: >
      [[[
        return (new Date()).toLocaleDateString("en-ZA", {timeZone: variables.timezone});
      ]]]
    icon: >
      [[[
        var hourNamesIndexed = ["twelve", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve"];
        var timeParts = (new Date()).toLocaleTimeString("en-ZA", {timeZone: variables.timezone, hour12: true}).split(':');
        var hour = parseInt(timeParts[0]);
        var minute = parseInt(timeParts[1]);
        return "mdi:clock-time-" + hourNamesIndexed[hour] + "-outline";
      ]]]
    color: var(--paper-item-icon-color)
    styles:
      grid:
        - grid-template-areas: '"n" "i" "s" "l"'
      name:
        - color: var(--secondary-text-color)
        - font-size: 1rem
      state:
        - color: var(--secondary-text-color)
        - font-size: 0.8rem
      label:
        - color: var(--secondary-text-color)
        - font-size: 0.8rem
    tap_action: none
  basic:
    size: 20%
    show_label: true
    color: var(--button-card-light-color)
    # this is just to create a phantom space to have it align better with other buttons on the same row
    label: >
      [[[
        return '_';
      ]]]
    styles:
      name:
        - color: var(--paper-item-icon-color)
      label:
        - color: var(--primary-background-color)
      card:
        - font-size: 12px
      grid:
        - grid-template-areas: '"l" "i" "n"'
        - grid-template-rows: min-content 1fr min-content
        - grid-template-columns: 1fr
    state:
      - value: 'unavailable'
        styles:
          icon:
            - color: var(--state-icon-unavailable-color)
    tap_action:
      action: toggle
      haptic: light
    hold_action:
      action: more-info
      haptic: selection
  light_with_timer:
    triggers_update: all
    size: 20%
    color: var(--button-card-light-color)
    styles:
      name:
        - color: var(--paper-item-icon-color)
      label:
        - color: var(--primary-background-color)
      card:
        - font-size: 12px
      grid:
        - grid-template-areas: '"t" "i" "n"'
        - grid-template-rows: min-content 1fr min-content
        - grid-template-columns: 1fr
    custom_fields:
      t:
        card:
          type: custom:button-card
          name: Timer
          entity: "[[[ return entity.entity_id.replace('light.', 'timer.') + '_timer'; ]]]"
          show_name: false
          show_icon: false
          show_state: true
          styles:
            card:
              - font-size: 12px
              - box-shadow: none
            state:
              - margin-top: -1ex
              - margin-bottom: -1ex
              - color: >
                  [[[
                    if (states[`${entity.entity_id}`.replace('light.', 'timer.') + '_timer'].state == 'idle')
                      return "var(--paper-item-icon-color)";
                    else
                      return "var(--custom-color-red)";
                  ]]]
          tap_action:
            action: none
          hold_action:
            action: none
    state:
      - value: 'unavailable'
        styles:
          icon:
            - color: var(--state-icon-unavailable-color)
    tap_action:
      action: toggle
      haptic: light
    double_tap_action:
      action: call-service
      haptic: medium
      service: script.turn_on_light_and_timer
      service_data:
        light: "[[[ return entity.entity_id; ]]]"
        duration: "00:03:00"
    hold_action:
      action: more-info
      haptic: selection
  rgb_light:
    variables:
      above_threshold: |
        [[[
          let threshold = 255;
          if (entity.state === 'on' && entity.attributes.rgb_color) {
            let rgb_sum = entity.attributes.rgb_color.reduce((a, b) => a + b, 0);
            return rgb_sum >= 3 * threshold;
          }
          return false;
        ]]]
    size: 20%
    color: var(--button-card-light-color)
    show_label: true
    label: >
      [[[
        var b = entity.attributes.brightness;
        return parseInt(b ? (b/255)*100 : '0') + '%';
      ]]]
    styles:
      name:
        - color: var(--paper-item-icon-color)
      label:
        - color: var(--paper-item-icon-color)
        - padding-left: 1ex
      # https://community.home-assistant.io/t/lovelace-button-card/65981/4599
      # https://community.home-assistant.io/t/lovelace-button-card/65981/4788
      icon:
        - color: |
            [[[
              if (variables.above_threshold) { // above threshold == white here
                return 'var(--paper-item-icon-active-color)';
              } else if (entity.state === 'on') {
                return 'var(--button-card-light-color)'; // already includes brightness/color support
              } else if (entity.state === 'off') { // off
                return 'var(--paper-item-icon-color)';
              } else { // unavailable
                return 'var(--primary-text-color)';
              }
            ]]]
        - filter: '[[[ return variables.above_threshold ? `brightness(${(entity.attributes.brightness/255 + 1)/2})` : null; ]]]'
      card:
        - font-size: 12px
      grid:
        - grid-template-areas: '"l" "i" "n"'
        - grid-template-rows: min-content 1fr min-content
        - grid-template-columns: 1fr
    state:
      - value: 'unavailable'
        styles:
          icon:
            - color: var(--state-icon-unavailable-color)
    tap_action:
      haptic: light
      action: call-service
      service: script.toggle_light
      service_data:
        light: "[[[ return entity.entity_id; ]]]"
        profile: "[[[ return variables.profile; ]]]"
    double_tap_action:
      action: call-service
      haptic: medium
      service: script.force_on_smart_bulb
      service_data:
        light: "[[[ return entity.entity_id; ]]]"
    hold_action:
      action: more-info
      haptic: selection
  rgb_light_with_timer:
    triggers_update: all
    styles:
      grid:
        - grid-template-areas: '"t s l" "i i i" "n n n"'
        - grid-template-rows: min-content 1fr min-content
        - grid-template-columns: 1fr min-content 1fr
      name:
        - margin-top: -1px
        - margin-bottom: 0px
      label:
        - align-self: middle
        - justify-self: start
        - padding-right: 1ex
      custom_fields:
        s:
          - color: var(--paper-item-icon-color)
        t:
          - align-self: middle
          - justify-self: end
          - padding-right: 1ex
    custom_fields:
      s: >
        [[[ return '/' ]]]
      t:
        card:
          type: custom:button-card
          name: Timer
          entity: "[[[ return entity.entity_id.replace('light.', 'timer.') + '_timer'; ]]]"
          show_name: false
          show_icon: false
          show_state: true
          styles:
            card:
              - margin-bottom: -1px
              - font-size: 12px
              - box-shadow: none
            state:
              - color: >
                  [[[
                    if (states[`${entity.entity_id}`.replace('light.', 'timer.') + '_timer'].state == 'idle')
                      return "var(--paper-item-icon-color)";
                    else
                      return "var(--custom-color-red)";
                  ]]]
          tap_action:
            action: none
          hold_action:
            action: none
    state:
      - value: 'unavailable'
        styles:
          icon:
            - color: var(--state-icon-unavailable-color)
    tap_action:
      haptic: light
      action: call-service
      service: script.toggle_light
      service_data:
        light: "[[[ return entity.entity_id; ]]]"
        profile: "[[[ return variables.profile; ]]]"
    double_tap_action:
      haptic: medium
      action: call-service
      service: script.toggle_light
      service_data:
        light: "[[[ return entity.entity_id; ]]]"
        profile: night
    hold_action:
      haptic: selection
      action: more-info
  cover_with_timer:
    triggers_update: all
    size: 20%
    show_name: true
    color_type: icon
    color: var(--paper-item-icon-color)
    custom_fields:
      t:
        card:
          type: custom:button-card
          name: Timer
          entity: "[[[ return entity.entity_id.replace('cover.', 'timer.') + '_timer'; ]]]"
          show_name: false
          show_icon: false
          show_state: true
          styles:
            card:
              - font-size: 12px
              - box-shadow: none
            state:
              - margin-top: -1ex
              - margin-bottom: -1ex
              - color: >
                  [[[
                    if (states[`${entity.entity_id}`.replace('cover.', 'timer.') + '_timer'].state == 'idle')
                      return "var(--paper-item-icon-color)";
                    else
                      return "var(--custom-color-red)";
                  ]]]
          tap_action:
            action: none
          hold_action:
            action: none
    styles:
      name:
        - color: var(--paper-item-icon-color)
      card:
        - font-size: 12px
      grid:
        - grid-template-areas: '"t" "i" "n"'
        - grid-template-rows: min-content 1fr min-content
        - grid-template-columns: 1fr
    state:
      - value: 'unavailable'
        styles:
          icon:
            - color: var(--state-icon-unavailable-color)
    tap_action:
      action: toggle
      haptic: light
    hold_action:
      action: call-service
      haptic: heavy
      service: timer.start
      service_data:
        entity_id: "[[[ return entity.entity_id.replace('cover.', 'timer.') + '_timer'; ]]]"
        duration: "00:10:00"
  cover_with_occupancy:
    triggers_update: all
    state:
      - operator: template
        value: >
          [[[
            return states[`${variables.occupancy_entity}`].state == 'on'
          ]]]
        color: var(--paper-item-icon-active-color)
      - operator: template
        value: >
          [[[
            return states[`${variables.occupancy_entity}`].state == 'off'
          ]]]
        color: var(--paper-item-icon-color)
      - value: 'unavailable'
        styles:
          icon:
            - color: var(--state-icon-unavailable-color)
    double_tap_action:
      action: call-service
      haptic: medium
      service: script.close_garage_door_and_main_gate
      service_data:
        garage_door: "[[[ return entity.entity_id; ]]]"
  shutdown:
    name: "[[[ return entity.attributes.friendly_name; ]]]"
    size: 30%
    styles:
      name:
        - color: var(--paper-item-icon-color)
      card:
        - font-size: 12px
    hold_action:
      action: call-service
      haptic: heavy
      service: script.shutdown_remote_host
      service_data:
        name: "[[[ return entity.attributes.friendly_name; ]]]"
        host: "[[[ return entity.attributes.friendly_name.toLowerCase(); ]]]"  # must match .ssh/config
      confirmation:
        text: "[[[ return `Are you sure you want to shut down ${entity.attributes.friendly_name}?` ]]]"
  restart:
    name: "[[[ return variables.name; ]]]"
    size: 20%
    styles:
      name:
        - color: var(--paper-item-icon-color)
      card:
        - font-size: 12px
    double_tap_action:
      action: call-service
      haptic: medium
      service: switch.turn_on
      service_data:
        entity_id: "[[[ return variables.switch_entity; ]]]"
      confirmation:
        text: "[[[ return `Are you sure you want to restart the ${variables.name.toLowerCase()} device?`; ]]]"
  remote:
    variables:
      selection: "Remote State"
    entity: input_select.selected_remote
    name: "[[[ return variables.selection ]]]"
    size: 50%
    color_type: icon
    styles:
      name:
        - color: var(--paper-item-icon-color)
      label:
        - color: var(--paper-item-icon-color)
        - padding-left: 1ex
      card:
        - font-size: 12px
      icon:
        - color: |
            [[[
              if (entity.state == variables.selection) {
                return 'var(--paper-item-icon-active-color)';
              } else  {
                return 'var(--paper-item-icon-color)';
              }
            ]]]
    tap_action:
      action: call-service
      haptic: light
      service: input_select.select_option
      service_data:
        entity_id: input_select.selected_remote
        option: "[[[ return variables.selection; ]]]"
