title: Home
background: var(--background-image)
views:
  - !include ui-lovelace/main.yaml
  - !include ui-lovelace/resources.yaml
  - !include ui-lovelace/environment.yaml
  - !include ui-lovelace/irrigation.yaml
  - !include ui-lovelace/baby.yaml
  - !include ui-lovelace/entertainment.yaml
  - !include ui-lovelace/internet.yaml
  - !include ui-lovelace/security.yaml
  - !include ui-lovelace/gallery.yaml
  - !include ui-lovelace/devices.yaml
  - !include ui-lovelace/test.yaml

button_card_templates: !include button_card_templates.yaml
