path: environment
title: Environment
icon: mdi:weather-partly-snowy-rainy
badges:
  - entity: sensor.living_room_ht_temperature
    name: Living Room
  - entity: sensor.main_bedroom_ht_temperature
    name: Main Bedroom
  - entity: sensor.outside_temperature
    name: Outside
  - entity: sensor.outside_feels_like
    name: Feels Like
  # https://community.home-assistant.io/t/hours-of-daylight/59422/
  # https://community.home-assistant.io/t/enhanced-sun-component/63553
  - entity: sensor.daylight_hm
    name: Daylight
  - entity: sensor.moon
    name: Moon Phase
cards:
  - type: vertical-stack
    cards:
      - type: custom:weather-card
        name: Stellies
        entity: weather.openweathermap_hourly
        current: true
        details: true
        forecast: true
        hourly_forecast: true
        number_of_forecasts: 5  # hours
      - type: custom:weather-card
        entity: weather.openweathermap_daily
        current: false
        details: false
        forecast: true
        hourly_forecast: false
        number_of_forecasts: 5  # days
      - type: history-graph
        hours_to_show: 72
        entities:
          - entity: weather.openweathermap_daily
            name: Today
          - entity: sensor.weather_forecast_conditions_tomorrow
            name: Tomorrow
      - type: custom:swipe-card
        parameters:
          autoHeight: true
          pagination:
            type: 'bullets'
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            entities:
              - entity: sensor.living_room_ht_temperature
                name: Living Room
                color: var(--custom-color-yellow)
              - entity: sensor.main_bedroom_ht_temperature
                name: Main Bedroom
                color: var(--custom-color-green)
              - entity: sensor.outside_temperature
                name: Outside
                color: var(--custom-color-red)
              - entity: sensor.outside_feels_like
                name: Feels Like
                color: var(--custom-color-magenta)
            hours_to_show: 24
            hour24: true
            smoothing: true
            points_per_hour: 12  # every 5 min
            line_width: 2
            show:
              extrema: true
              average: true
          - type: custom:mini-graph-card
            name: Humidity
            entities:
              - entity: sensor.living_room_ht_humidity
                name: Living Room
                color: var(--custom-color-blue)
              - entity: sensor.main_bedroom_ht_humidity
                name: Main Bedroom
                color: var(--custom-color-magenta)
            hours_to_show: 24
            hour24: true
            smoothing: true
            points_per_hour: 2  # every 30 min
            line_width: 2
            show:
              extrema: true
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          # don't use this if you want to use thresholds: color overrides
          # sensor.sun_illuminance can be very unreliable (operationally); need to use my own light meter
          # - entity: sensor.sun_illuminance
          #   color: var(--custom-color-yellow)
          - entity: sensor.illuminance
            color: var(--custom-color-yellow)
          - entity: sensor.solar_angle
            color: var(--custom-color-red)
            y_axis: secondary
        hours_to_show: 24
        hour24: true
        smoothing: true
        points_per_hour: 12  # every 5 min
        line_width: 2
        lower_bound: 0
        upper_bound: 10000
        show:
          extrema: true
        # color_thresholds:
        #   # https://community.home-assistant.io/t/outdoor-illuminance-template-sensor/228581
        #   - value: 10  # min
        #     color: var(--custom-color-gray)
        #   - value: 10000  # max
        #     color: var(--custom-color-yellow)
      - type: history-graph
        title: Low Light Sensor
        hours_to_show: 24
        entities:
          - entity: binary_sensor.low_light
            name: Low Light
        # https://www.wikihow.com/Compute-the-UV-Index
        # https://www.ehso.com/uvIndexCalc.htm
        # https://www.who.int/news-room/q-a-detail/radiation-ultraviolet-(uv)
        # https://en.wikipedia.org/wiki/Ultraviolet_index
      - type: custom:mini-graph-card
        name: UV
        icon: mdi:weather-sunny-alert
        entities:
          - entity: sensor.openweathermap_uv_index
            name: UV Index
        lower_bound: 0
        hours_to_show: 24
        hour24: true
        smoothing: true
        points_per_hour: 1
        line_width: 2
        show:
          extrema: true
        color_thresholds:
          - value: 0
            color: var(--custom-color-green)
          - value: 4
            color: var(--custom-color-yellow)
          - value: 7
            color: var(--custom-color-red)
      - type: entities
        show_header_toggle: false
        entities:
          - entity: sensor.uva_irradiance
            name: UVA
          - entity: sensor.uvb_irradiance
            name: UVB
      - type: entities
        title: Dam Levels
        show_header_toggle: false
        entities:
          - entity: sensor.steenbras_upper_dam_level
            name: Steenbras Upper
          - entity: sensor.steenbras_lower_dam_level
            name: Steenbras Lower
          - entity: sensor.bergrivier_dam_level
            name: Bergrivier
          - entity: sensor.theewaterskloof_dam_level
            name: Theewaterskloof
          - entity: sensor.voelvlei_dam_level
            name: Voëlvlei
          - entity: sensor.wemmershoek_dam_level
            name: Wemmershoek
          - entity: sensor.total_dam_level
            name: Overall
          - entity: sensor.dam_levels_last_update
            name: Last Update
  - type: vertical-stack
    cards:
      - type: custom:swipe-card
        parameters:
          autoHeight: true
          pagination:
            type: 'bullets'
        cards:
          - type: custom:mini-graph-card
            name: Air Quality
            icon: mdi:lungs
            entities:
              - entity: sensor.owm_pollution_overall_air_quality
                name: AQI
            lower_bound: 0
            hours_to_show: 24
            hour24: true
            smoothing: true
            points_per_hour: 1
            line_width: 2
            show:
              extrema: true
            color_thresholds:
              - value: 0
                color: var(--custom-color-green)
              - value: 50
                color: var(--custom-color-yellow)
              - value: 100
                color: var(--custom-color-red)
          - type: custom:mini-graph-card
            name: PM 2.5
            icon: mdi:grain
            entities:
              - entity: sensor.owm_pollution_fine_particles_pm2_5
                name: OWM
              - entity: sensor.saaqis_pm_2_5
                name: SAAQIS
                y_axis: secondary
            lower_bound: 0
            hours_to_show: 24
            hour24: true
            smoothing: true
            points_per_hour: 1
            line_width: 2
            show:
              extrema: true
          - type: custom:mini-graph-card
            name: PM 10
            icon: mdi:grain
            entities:
              - entity: sensor.owm_pollution_coarse_particles_pm10
                name: OWM
              - entity: sensor.saaqis_pm_10
                name: SAAQIS
                y_axis: secondary
            lower_bound: 0
            hours_to_show: 24
            hour24: true
            smoothing: true
            points_per_hour: 1
            line_width: 2
            show:
              extrema: true
          - type: custom:mini-graph-card
            name: NO₂
            icon: mdi:smog
            entities:
              - entity: sensor.owm_pollution_nitrogen_dioxide_no2
                name: OWM
              - entity: sensor.saaqis_no2
                name: SAAQIS
                y_axis: secondary
            lower_bound: 0
            hours_to_show: 24
            hour24: true
            smoothing: true
            points_per_hour: 1
            line_width: 2
            show:
              extrema: true
          - type: custom:mini-graph-card
            name: SO₂
            icon: mdi:smog
            entities:
              - entity: sensor.owm_pollution_sulphur_dioxide_so2
                name: OWM
              - entity: sensor.saaqis_so2
                name: SAAQIS
                y_axis: secondary
            lower_bound: 0
            hours_to_show: 24
            hour24: true
            smoothing: true
            points_per_hour: 1
            line_width: 2
            show:
              extrema: true
          - type: custom:mini-graph-card
            name: O₃
            icon: mdi:skull-outline
            entities:
              - entity: sensor.owm_pollution_ozone_o3
                name: OWM
              - entity: sensor.saaqis_o3
                name: SAAQIS
                y_axis: secondary
            lower_bound: 0
            hours_to_show: 24
            hour24: true
            smoothing: true
            points_per_hour: 1
            line_width: 2
            show:
              extrema: true
      - type: horizontal-stack
        cards:
          # https://en.wikipedia.org/wiki/Air_quality_index
          # https://www.environment.gov.za/sites/default/files/legislations/nemaqa_airquality_g32816gon1210_0.pdf
          # https://www.airveda.com/blog/AQI-calculation-update
          - type: gauge
            name: PM2.5
            entity: sensor.owm_pollution_fine_particles_pm2_5
            min: 0
            max: 400
            severity:
              green: 0
              yellow: 90
              red: 180
          - type: gauge
            name: PM10
            entity: sensor.owm_pollution_coarse_particles_pm10
            min: 0
            max: 430
            severity:
              green: 0
              yellow: 100
              red: 250
      - type: horizontal-stack
        cards:
          - type: gauge
            name: NO₂
            entity: sensor.owm_pollution_nitrogen_dioxide_no2
            min: 0
            max: 400
            severity:
              green: 0
              yellow: 80
              red: 180
          - type: gauge
            name: SO₂
            entity: sensor.owm_pollution_sulphur_dioxide_so2
            min: 0
            max: 1600
            severity:
              green: 0
              yellow: 80
              red: 380
          - type: gauge
            name: O₃
            entity: sensor.owm_pollution_ozone_o3
            min: 0
            max: 170
            severity:
              green: 0
              yellow: 100
              red: 170
      - type: horizontal-stack
        cards:
          - type: gauge
            name: "NO"
            entity: sensor.owm_pollution_nitrogen_monoxide_no
            # hard to find these... just setting it the same as for no2
            # https://apps.who.int/iris/bitstream/handle/10665/39555/9241540648-eng.pdf
            min: 0
            max: 400
            severity:
              green: 0
              yellow: 80
              red: 180
          - type: gauge
            name: CO
            entity: sensor.owm_pollution_carbon_monoxide_co
            min: 0
            max: 34000
            severity:
              green: 0
              yellow: 2000
              red: 10000
          - type: gauge
            name: NH₃
            entity: sensor.owm_pollution_ammonia_nh3
            min: 0
            max: 1800
            severity:
              green: 0
              yellow: 400
              red: 800
      - type: entities
        show_header_toggle: true
        entities:
          - entity: sensor.owm_pollution_fine_particles_pm2_5
            type: custom:multiple-entity-row
            name: PM2.5
            state_header: OWM
            entities:
              - entity: sensor.saaqis_pm_2_5
                name: SAAQIS
          - entity: sensor.owm_pollution_coarse_particles_pm10
            type: custom:multiple-entity-row
            name: PM10
            state_header: OWM
            entities:
              - entity: sensor.saaqis_pm_10
                name: SAAQIS
          - entity: sensor.owm_pollution_nitrogen_dioxide_no2
            type: custom:multiple-entity-row
            name: NO₂
            state_header: OWM
            entities:
              - entity: sensor.saaqis_no2
                name: SAAQIS
          - entity: sensor.owm_pollution_sulphur_dioxide_so2
            type: custom:multiple-entity-row
            name: SO₂
            state_header: OWM
            entities:
              - entity: sensor.saaqis_so2
                name: SAAQIS
          - entity: sensor.owm_pollution_ozone_o3
            type: custom:multiple-entity-row
            name: O₃
            state_header: OWM
            entities:
              - entity: sensor.saaqis_o3
                name: SAAQIS
