title: Security
path: security
icon: mdi:security
badges:
  - type: entity
    entity: binary_sensor.kitchen_smoke
    name: Kitchen
    show_icon: true
    show_name: true
    show_state: false
  - type: entity
    entity: binary_sensor.doorbell_rang
    name: Doorbell
    show_icon: true
    show_name: true
    show_state: false
  - type: entity
    entity: binary_sensor.doorbell_motion_detected
    name: Doorbell
    show_icon: true
    show_name: true
    show_state: false
  - type: entity
    entity: binary_sensor.foyer_motion_detected
    name: Foyer
    show_icon: true
    show_name: true
    show_state: false
  - type: entity
    entity: binary_sensor.cabinet_door
    name: Cabinet
    show_icon: true
    show_name: true
    show_state: false
cards:
  - type: vertical-stack
    cards:
      - type: picture-glance
        title: Doorbell Camera
        camera_image: camera.doorbell
        camera_view: auto
        entities:
          - binary_sensor.doorbell_rang
          - binary_sensor.doorbell_motion_detected
          # blocking call
          - entity: script.take_snapshot
            tap_action:
              action: call-service
              service: script.take_snapshot
              data:
                camera_entity_id: camera.doorbell
                subdirectory: "doorbell"
      # https://community.home-assistant.io/t/styling-tile-cards/696907/10
      # https://community.home-assistant.io/t/card-mod-for-tile-card-icon-tile-color/657214/52
      - type: tile
        entity: alarm_control_panel.home
        name: "Home Alarm"
        features:
          - type: "alarm-modes"
            modes:
              - armed_home
              - armed_away
              - disarmed
        # this works in conjunction with www/custom.js
        card_mod: &alarm_mods
          style:
            hui-card-features $ hui-alarm-modes-card-feature $ div ha-control-select $ div: |
              #option-armed_home {
                --control-select-color: #ffa800 !important;
              }
              #option-armed_away {
                --control-select-color: #aa0000 !important;
              }
              #option-disarmed {
                --control-select-color: #40b100 !important;
              }
            hui-card-features $ div hui-card-feature $ hui-alarm-modes-card-feature $ ha-control-button-group ha-control-button $ button: |
              .button {
                background-color: #40b100 !important;
              }
      - type: tile
        entity: alarm_control_panel.flatlet
        name: "Flatlet Alarm"
        features:
          - type: "alarm-modes"
            modes:
              - armed_away
              - disarmed
        card_mod: *alarm_mods
      # todo: panic button (mdi:alert-outline/mdi:shield-alert-outline)
      - type: history-graph
        hours_to_show: 24
        entities:
          - entity: alarm_control_panel.home
            name: Home
          - entity: alarm_control_panel.flatlet
            name: Flatlet
      - type: custom:home-feed-card
        title: Events
        show_empty: true
        max_item_count: 20
        state_color: false
        compact_mode: true
        show_icons: false
        max_height: 14em
        entities:
          - entity: binary_sensor.doorbell_rang
            include_history: true
            max_history: 5
            remove_repeats: false
            exclude_states:
              - "off"
              - "unknown"
              - "unavailable"
            format: datetime
            content_template: "Doorbell rang"
          - entity: cover.main_gate
            include_history: true
            max_history: 5
            remove_repeats: false
            exclude_states:
              - "closed"
              - "unknown"
              - "unavailable"
            format: datetime
            state_map:
              open: "opened"
            content_template: "Main gate {{state}}"
          - entity: cover.garage_doors_lhs
            include_history: true
            max_history: 5
            remove_repeats: false
            exclude_states:
              - "closed"
              - "unknown"
              - "unavailable"
            format: datetime
            state_map:
              open: "opened"
            content_template: "Rouvé's garage door {{state}}"
          - entity: cover.garage_doors_rhs
            include_history: true
            max_history: 5
            remove_repeats: false
            exclude_states:
              - "closed"
              - "unknown"
              - "unavailable"
            format: datetime
            state_map:
              open: "opened"
            content_template: "Pieter's garage door {{state}}"
          - entity: alarm_control_panel.home
            include_history: true
            max_history: 5
            remove_repeats: false
            exclude_states:
              - "unknown"
              - "unavailable"
            format: datetime
            state_map:
              disarmed: "disarmed"
              armed_home: "armed (stay)"
              armed_away: "armed"
            content_template: "Home alarm was {{state}}"
          - entity: alarm_control_panel.flatlet
            include_history: true
            max_history: 5
            remove_repeats: false
            exclude_states:
              - "unknown"
              - "unavailable"
            format: datetime
            state_map:
              disarmed: "disarmed"
              armed_away: "armed"
            content_template: "Flatlet alarm was {{state}}"
          - entity: binary_sensor.kitchen_smoke
            include_history: true
            max_history: 5
            remove_repeats: false
            exclude_states:
              - "off"
              - "unknown"
              - "unavailable"
            format: datetime
            content_template: "Smoke was detected in the kitchen"
      - type: entities
        title: "Gates & Doors"
        show_header_toggle: false
        entities:
          - entity: cover.main_gate
          - entity: cover.garage_doors_lhs
            name: Rouvé's Garage Door (LHS)
          - entity: cover.garage_doors_rhs
            name: Pieter's Garage Door (RHS)
      - type: history-graph
        hours_to_show: 24
        entities:
          - entity: cover.main_gate
            name: Gate
          - entity: cover.garage_doors_lhs
            name: Rouvé
          - entity: cover.garage_doors_rhs
            name: Pieter
          - entity: light.garage
            name: Garage L.
          - entity: light.front_door
            name: Front Door L.
          - entity: light.backyard
            name: Backyard L.
      - type: entities
        entities:
          - entity: timer.main_gate_timer
            name: Main Gate Open Timeout
          - entity: timer.garage_doors_lhs_timer
            name: Rouvé's Garage Door Open Timeout (LHS)
          - entity: timer.garage_doors_rhs_timer
            name: Pieter's Garage Door Open Timeout (RHS)
      - type: history-graph
        title: Vehicles
        hours_to_show: 24
        entities:
          - entity: binary_sensor.garage_doors_lhs_occupied
            name: Rouvé
          - entity: binary_sensor.garage_doors_rhs_occupied
            name: Pieter
  - type: vertical-stack
    cards:
      - type: picture-glance
        title: Security Camera
        camera_image: camera.security_camera_proxy
        camera_view: auto
        entities:
          - binary_sensor.foyer_motion_detected
          - entity: script.security_camera_create_snapshot
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.security_camera_create_snapshot
          - entity: script.security_camera_record_clip
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.security_camera_record_clip
          - entity: light.foyer
            tap_action:
              action: call-service
              service: script.toggle_light
              service_data:
                light: light.foyer
                profile: security
          - group.security_automations
      - type: custom:swipe-card
        parameters:
          autoHeight: true
          pagination:
            type: 'bullets'
        cards:
          - type: picture-glance
            title: Last Snapshot Captured
            camera_image: camera.security_camera_last_snapshot
            entities: []
            card_mod:
              style: |
                .title:after {
                  content: ": {{ states('sensor.security_camera_last_snapshot_relative') }}";
                }
          - type: picture-glance
            title: Last Clip Captured
            camera_image: camera.security_camera_last_clip
            entities: []
            card_mod:
              style: |
                .title:after {
                  content: ": {{ states('sensor.security_camera_last_clip_relative') }}";
                }
      - type: entities
        entities:
          - entity: sensor.motion_detected_last_relative
            name: Last Motion Detected
          - entity: timer.living_room_lamp_timer
            name: Living Room Lamp
          - entity: timer.foyer_timer
            name: Foyer Light
          - entity: group.security_automations
            name: Snapshots and Lights
      - type: history-graph
        title: Movement
        hours_to_show: 24
        entities:
          - entity: binary_sensor.doorbell_motion_detected
            name: Doorbell
          - entity: binary_sensor.foyer_occupancy_homebridge
            name: Foyer M.
          - entity: light.foyer
            name: Foyer L.
          - entity: light.living_room_lamp
            name: Living R. Lamp
      - type: statistics-graph
        entities:
          - entity: sensor.doorbell_motion_detections
            name: Doorbell
        days_to_show: 7
        period: day
        chart_type: bar
        stat_types:
          - state
      - type: statistics-graph
        entities:
          - entity: sensor.foyer_motion_detections
            name: Foyer
        days_to_show: 7
        period: day
        chart_type: bar
        stat_types:
          - state
