# https://community.home-assistant.io/t/fsr-the-best-bed-occupancy-sensor/365795

substitutions:
  device_name_upper: "Bed Occupancy"
  device_name_lower: "bed_occupancy"

esphome:
  name: bed-occupancy

esp8266:
  board: d1_mini
  framework:
    version: recommended

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      # pressed => low
      inverted: true
    name: "${device_name_upper} Bed Occupied"
    id: "${device_name_lower}_bed_occupied"
    device_class: occupancy
    filters:
      # debounce press
      - delayed_on: 50ms
      # avoid flicker when released
      - delayed_off: 500ms

  - platform: status
    id: ${device_name_lower}_status
    name: "${device_name_upper} Status"

switch:
  - platform: restart
    id: ${device_name_lower}_restart
    name: "${device_name_upper} Restart"
