# https://community.home-assistant.io/t/fsr-the-best-bed-occupancy-sensor/365795

substitutions:
  device_name_upper: "Bed Occupancy"
  device_name_lower: "bed_occupancy"

esphome:
  name: bed-occupancy

esp8266:
  board: d1_mini
  framework:
    version: recommended

wifi:
  power_save_mode: none
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name_upper} Fallback Hotspot"
    password: !secret fallback_ap_password

<<: !include common.yaml

number:
  - platform: template
    name: "${device_name_upper} Trigger Level"
    id: "${device_name_lower}_trigger_level"
    icon: mdi:menu
    initial_value: 1
    restore_value: true
    optimistic: true
    unit_of_measurement: V
    min_value: 0
    max_value: 3.5
    step: 0.05

sensor:
  - platform: adc
    pin: A0
    name: "${device_name_upper} Signal"
    id: "${device_name_lower}_signal"
    icon: mdi:bed
    unit_of_measurement: V
    update_interval: 0.5s
    filters:
      - multiply: 3.3
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      - or:
          - throttle: 10s
          - delta: 0.02

binary_sensor:
  - platform: template
    name: "${device_name_upper} Bed Occupied"
    id: "${device_name_lower}_bed_occupied"
    device_class: occupancy
    lambda: |-
      if (id(${device_name_lower}_signal).state < id(${device_name_lower}_trigger_level).state) {
        return true;
      } else {
        return false;
      }

switch:
  - platform: restart
    id: ${device_name_lower}_restart
    name: "${device_name_upper} Restart"
