esphome:
  name: garage-doors
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.0.12
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Doors Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:

# Enable logging
logger:

ota:
  password: !secret ota_password

# https://esphome.io/components/binary_sensor/gpio.html
binary_sensor:
  - platform: gpio
    id: rhs_garage_door_status
    name: "RHS Garage Door Status"
    device_class: garage_door
    pin:
      number: 32
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_on: 1000ms
      - delayed_off: 1000ms
  - platform: gpio
    id: lhs_garage_door_status
    name: "LHS Garage Door Status"
    device_class: garage_door
    pin:
      number: 35
      # WARNING: no internal pull-up: must add this as part of the circuit
      inverted: True
    filters:
      - delayed_on: 1000ms
      - delayed_off: 1000ms
  # 100cm / 1m
  # true => occupied; false => empty
  - platform: template
    name: "LHS Garage Occupied"
    lambda: |-
      if (id(lhs_garage_ultrasonic_sensor).state < 1) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "RHS Garage Occupied"
    lambda: |-
      if (id(rhs_garage_ultrasonic_sensor).state < 1) {
        return true;
      } else {
        return false;
      }

# https://esphome.io/components/switch/gpio.html
switch:
  - platform: gpio
    id: rhs_garage_door_control
    name: "RHS Garage Door Control"
    pin: 12
    restore_mode: ALWAYS_OFF
  - platform: template
    id: rhs_garage_door_remote
    name: "RHS Garage Door Remote"
    icon: "mdi:remote"
    restore_state: False
    turn_on_action:
      - switch.turn_on: rhs_garage_door_control
      - delay: 500ms
      - switch.turn_off: rhs_garage_door_control
  - platform: gpio
    id: lhs_garage_door_control
    name: "LHS Garage Door Control"
    pin: 14
    restore_mode: ALWAYS_OFF
  - platform: template
    id: lhs_garage_door_remote
    name: "LHS Garage Door Remote"
    icon: "mdi:remote"
    restore_state: False
    turn_on_action:
      - switch.turn_on: lhs_garage_door_control
      - delay: 500ms
      - switch.turn_off: lhs_garage_door_control
  - platform: restart
    id: garage_doors_restart
    name: "Garage Doors Restart"

sensor:
  - platform: ultrasonic
    id: lhs_garage_ultrasonic_sensor
    name: "LHS Garage Ultrasonic Sensor"
    icon: "mdi:contactless-payment"
    trigger_pin: 26
    echo_pin: 27
    update_interval: 60s
  - platform: ultrasonic
    id: rhs_garage_ultrasonic_sensor
    name: "RHS Garage Ultrasonic Sensor"
    icon: "mdi:contactless-payment"
    trigger_pin: 33
    echo_pin: 25
    update_interval: 60s

mqtt:
  broker: !secret mqtt_broker
  discovery: True
