substitutions:
  device_name_upper: "Office"
  device_name_lower: "office"

esphome:
  name: office
  platform: ESP32
  board: nodemcu-32s

wifi:
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.0.14
    gateway: !secret gateway
    subnet: !secret subnet
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name_upper} Fallback Hotspot"
    password: !secret fallback_ap_password

<<: !include common.yaml

globals:
 - id: on_air
   type: bool
   restore_value: no
   initial_value: "false"

# https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

sensor:
  - platform: dht
    model: AM2302
    pin: 33
    temperature:
      name: "${device_name_upper} Temperature"
      id: ${device_name_lower}_temperature
      # https://community.home-assistant.io/t/debug-esphome-sensors/134688/18
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10
        # psql -U homeassistant -d homeassistant
        # \copy (select state, last_updated from states where entity_id='sensor.office_temperature'         and last_updated >= '2022-10-05 00:00:00' and state not in ('unavailable', 'unknown')) to '/tmp/sensor.officetemperature.csv'          with csv delimiter ',' header;
        # \copy (select state, last_updated from states where entity_id='sensor.living_room_ht_temperature' and last_updated >= '2022-10-05 00:00:00' and state not in ('unavailable', 'unknown')) to '/tmp/sensor.living_room_ht_temperature.csv' with csv delimiter ',' header;
        # scp homeassistant:/tmp/*.csv ~/Downloads/
        # python snippet:
        # import pandas as pd
        # og = pd.read_csv('sensor.officetemperature.csv')
        # og.last_updated = pd.to_datetime(og.last_updated)
        # og.sort_values('last_updated', inplace=True)
        # lr = pd.read_csv('sensor.living_room_ht_temperature.csv')
        # lr.last_updated = pd.to_datetime(lr.last_updated)
        # lr.sort_values('last_updated', inplace=True)
        # m = pd.merge_asof(og, lr, on='last_updated', tolerance=pd.Timedelta('10m'), direction='nearest'); m.to_csv('m.csv')
        # analysis:
        # https://docs.google.com/spreadsheets/d/1HlYbVSwn8k-v0HDMvln82tImMEC4XfoL9Mw6YFeTd-4/edit#gid=1691333222
        # - lambda: return 1.05*x - 3;
        - lambda: return x - 2;
    humidity:
      name: "${device_name_upper} Humidity"
      id: ${device_name_lower}_humidity
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10
    update_interval: 60s
  # https://community.home-assistant.io/t/outdoor-lux-sensor/421926
  # hint: use twisted pairs for long cables
  - platform: bh1750
    name: "${device_name_upper} Illuminance"
    id: ${device_name_lower}_illuminance
    address: 0x23  # low (0x5C if addr pin is pulled high)
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 15
          send_first_at: 3
  - platform: internal_temperature
    id: ${device_name_lower}_device_temperature
    name: "${device_name_upper} Device Temperature"

# https://microcontrollerslab.com/led-dot-matrix-display-esp32-max7219/
spi:
  clk_pin: 18  # D0
  mosi_pin: 23  # D1

font:
  - file: "fonts/pixelmix/pixelmix.ttf"
    id: pixelmix
    size: 8

display:
  - platform: max7219digit
    cs_pin: 5  # D2
    num_chips: 4
    intensity: 1  # 0..15
    lambda: |-
      if (id(on_air)) {
        it.print(0, 0, id(pixelmix), "ON AIR");
      } else {
        it.printf(it.get_width(), 0, id(pixelmix), TextAlign::TOP_RIGHT, "%.1f°C", id(office_temperature).state);
      }

switch:
  - platform: restart
    id: ${device_name_lower}_restart
    name: "${device_name_upper} Restart"
  # https://frenck.dev/diy-smart-doorbell-for-just-2-dollar/
  # https://www.reddit.com/r/homeassistant/comments/kxtp41/comment/gl5w556/?utm_source=share&utm_medium=web2x&context=3
  - platform: template
    id: ${device_name_lower}_on_air
    name: "${device_name_upper} On Air"
    lambda: |-
      return id(on_air);
    turn_on_action:
      - globals.set:
          id: on_air
          value: "true"
    turn_off_action:
      - globals.set:
          id: on_air
          value: "false"
