substitutions:
  device_name_upper: "Sonoff Basic"
  device_name_lower: "sonoff_basic"

esphome:
  name: sonoff-basic

esp8266:
  board: esp8285

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${device_name_upper} Button"
    on_press:
      - switch.toggle: "${device_name_lower}_relay"

switch:
  - platform: gpio
    name: "${device_name_upper} Relay"
    pin: GPIO12
    id: "${device_name_lower}_relay"

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - if:
              condition:
                api.connected:
              then:
                - output.turn_on: blue_led
              else:
                - output.turn_on: blue_led
                - delay: 500ms
                - output.turn_off: blue_led
                - delay: 500ms
          - output.turn_on: blue_led
        else:
          - output.turn_off: blue_led
