homeassistant:
  customize:
    sensor.pieter_activity_type:
      friendly_name: Pieter's Current Activity
    sensor.pieter_activity_confidence:
      friendly_name: Pieter's Activity Confidence
    binary_sensor.pieter_driving:
      icon: mdi:car

proximity:
  home:  # this refers to zone.home
    zone: home
    devices:
      - device_tracker.ceres
    tolerance: 20
    unit_of_measurement: m

input_boolean:
  pieter_driving:
    name: Pieter Driving
    icon: mdi:car

binary_sensor:
  - platform: template
    sensors:
      pieter_driving:
        friendly_name: "Pieter Driving"
        value_template: >-
          {{ is_state("input_boolean.pieter_driving", "on") }}

sensor:
  # https://github.com/home-assistant/core/issues/87941
  - platform: filter
    name: google_travel_time_filtered
    entity_id: sensor.google_travel_time
    filters:
      filter: lowpass
      time_constant: 10
      precision: 0

  - platform: template
    sensors:
      # https://companion.home-assistant.io/docs/core/sensors/
      pieter_activity_type:
        value_template: "{{ state_attr('sensor.ceres_activity', 'Types') | first }}"
        icon_template: "{{ state_attr('sensor.ceres_activity', 'icon') }}"
      pieter_activity_confidence:
        value_template: "{{ state_attr('sensor.ceres_activity', 'Confidence') }}"
        icon_template: >-
          {% if is_state_attr('sensor.ceres_activity', 'Confidence', 'High') %}
            mdi:speedometer
          {% elif is_state_attr('sensor.ceres_activity', 'Confidence', 'Medium') %}
            mdi:speedometer-medium
          {% elif is_state_attr('sensor.ceres_activity', 'Confidence', 'Low') %}
            mdi:speedometer-slow
          {% else %}
            unknown
          {% endif %}

automation:
  - alias: "Set Pieter's Driving State"
    id: "2cc8c07c-384d-4fce-ab9e-11e2c7a25b60"
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.pieter_activity_type
        to: "Automotive"  # from anything else
      - platform: state
        entity_id: sensor.pieter_activity_type
        from: "Automotive"  # to anything else
    action:
      - service: "input_boolean.turn_{{ 'on' if is_state('sensor.pieter_activity_type', 'Automotive') else 'off' }}"
        entity_id: input_boolean.pieter_driving

  - alias: "Notify If Driving State Changed"
    id: "e614d071-e6b5-4b20-bc33-5c946e6a1400"
    initial_state: false
    trigger:
      platform: state
      entity_id: binary_sensor.pieter_driving
    action:
      - service: notify.mobile_app_ceres
        data:
          title: "🚘 Test"
          message: "Pieter is{{ ' not' if is_state('binary_sensor.pieter_driving', 'off') }} driving."
          data:
            url: homeassistant://navigate/lovelace/devices

  - alias: "Proximity Updates"
    id: "355d7452-0b56-468b-b434-d0f4b430078b"
    initial_state: false
    trigger:
      - platform: state
        entity_id: proximity.home
    action:
      - service: persistent_notification.create
        data:
          title: Proximity
          message: >-
            Distance: {{ states('proximity.home') }}{{ state_attr('proximity.home', 'unit_of_measurement') }}; Direction of travel: {{ state_attr('proximity.home', 'dir_of_travel') }}.
