homeassistant:
  customize:
    sensor.pieter_activity_type:
      friendly_name: Pieter's Current Activity
    sensor.pieter_activity_confidence:
      friendly_name: Pieter's Activity Confidence
    binary_sensor.pieter_driving:
      icon: mdi:car

input_boolean:
  pieter_driving:
    name: Pieter Driving
    icon: mdi:car

sensor:
  # https://github.com/home-assistant/core/issues/87941: fixed
  - platform: filter
    name: google_travel_time_filtered
    entity_id: sensor.google_travel_time
    filters:
      filter: lowpass
      time_constant: 10
      precision: 0

template:
  - binary_sensor:
      - name: "Pieter Driving"
        unique_id: "a3f29d8b-6c59-4f0a-9be7-4a4264d99127"
        state: "{{ is_state('input_boolean.pieter_driving', 'on') }}"
  - sensor:
      # https://companion.home-assistant.io/docs/core/sensors/
      - name: Pieter Activity Type
        unique_id: "d7b7e8aa-ea5c-4e66-a2b5-59df16258407"
        icon: '{{ state_attr(''sensor.ceres_activity'', ''icon'') }}'
        state: '{{ state_attr(''sensor.ceres_activity'', ''Types'') | first }}'
  - sensor:
      - name: Pieter Activity Confidence
        unique_id: "6cf23bbb-3455-47b2-b6b3-e2224c71870a"
        icon: >-
          {% if is_state_attr('sensor.ceres_activity', 'Confidence', 'High') %}
            mdi:speedometer
          {% elif is_state_attr('sensor.ceres_activity', 'Confidence', 'Medium') %}
            mdi:speedometer-medium
          {% elif is_state_attr('sensor.ceres_activity', 'Confidence', 'Low') %}
            mdi:speedometer-slow
          {% else %}
            unknown
          {% endif %}
        state: "{{ state_attr('sensor.ceres_activity', 'Confidence') }}"

automation:
  - alias: "Set Pieter's Driving State"
    id: "2cc8c07c-384d-4fce-ab9e-11e2c7a25b60"
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.ceres_activity
    action:
      - service: "input_boolean.turn_{{ 'on' if 'Automotive' in state_attr('sensor.ceres_activity', 'Types') else 'off' }}"
        entity_id: input_boolean.pieter_driving

  - alias: "Notify If Driving State Changed"
    id: "e614d071-e6b5-4b20-bc33-5c946e6a1400"
    initial_state: false
    trigger:
      platform: state
      entity_id: binary_sensor.pieter_driving
    action:
      - service: notify.mobile_app_ceres
        data:
          title: "🚘 Test"
          message: "Pieter is{{ ' not' if is_state('binary_sensor.pieter_driving', 'off') }} driving."
          data:
            url: homeassistant://navigate/lovelace-system/devices
