proximity:
  home:  # this refers to zone.home
    zone: home
    devices:
      - device_tracker.ceres
    tolerance: 20
    unit_of_measurement: m

# https://www.dahuasecurity.com/products/All-Products/Video-Intercoms/IP-Products/Door-Stations/VTO2211G-WP
# https://amcrest.com/smarthome-2-megapixel-wireless-doorbell-security-camera-1920-x-1080p-wifi-doorbell-camera-ip55-weatherproof-two-way-audio-ad110.html
# https://www.hikvision.com/en/products/Video-Intercom-Products/
# https://github.com/rroller/dahua
# https://community.home-assistant.io/t/amcrest-doorbell-ad110-api-local-only/223838
# https://community.home-assistant.io/t/dahua-vto-custom-integration/293693
amcrest:
  - name: Doorbell
    host: !secret doorbell_host
    username: !secret doorbell_username
    password: !secret doorbell_password
    binary_sensors:
      - online
      - motion_detected

binary_sensor:
  - platform: template
    sensors:
      pieter_driving:
        friendly_name: "Pieter Driving"
        value_template: >-
          {{ is_state("input_boolean.pieter_driving", "on") }}

automation:
  - alias: "Set Pieter's Driving State"
    id: "2cc8c07c-384d-4fce-ab9e-11e2c7a25b60"
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.pieter_activity_type
        to: "Automotive"  # from anything else
      - platform: state
        entity_id: sensor.pieter_activity_type
        from: "Automotive"  # to anything else
    action:
      - service: "input_boolean.turn_{{ 'on' if is_state('sensor.pieter_activity_type', 'Automotive') else 'off' }}"
        entity_id: input_boolean.pieter_driving

  - alias: "Notify If Driving State Changed"
    id: "e614d071-e6b5-4b20-bc33-5c946e6a1400"
    initial_state: false
    trigger:
      platform: state
      entity_id: binary_sensor.pieter_driving
    action:
      - service: notify.mobile_app_ceres
        data:
          title: "Test"
          message: "Pieter is{{ ' not' if is_state('binary_sensor.pieter_driving', 'off') }} driving."
          data:
            url: homeassistant://navigate/lovelace/devices

  - alias: "Proximity Updates"
    id: "355d7452-0b56-468b-b434-d0f4b430078b"
    initial_state: false
    trigger:
      - platform: state
        entity_id: proximity.home
    action:
      - service: persistent_notification.create
        data:
          title: Proximity
          message: >-
            Distance: {{ states('proximity.home') }}{{ state_attr('proximity.home', 'unit_of_measurement') }}; Direction of travel: {{ state_attr('proximity.home', 'dir_of_travel') }}.
