input_select:
  selected_remote:
    name: Remote
    options:
      - TV
      - Audio
      - Apple TV
      - Satellite
    initial: Audio
    icon: mdi:remote-tv

media_player:
  - platform: universal
    name: Living Room Universal
    children:
      - media_player.living_room
    commands:
      turn_on:
        service: script.entertainment_apple_tv_on
      turn_off:
        service: script.entertainment_off
      volume_up:
        service: script.hk_3380_vol_up
      volume_down:
        service: script.hk_3380_vol_down
      volume_mute:
        service: script.hk_3380_mute
  - platform: shairport_sync
    name: Main Bedroom
    topic: shairport-sync/main-bedroom
  - platform: universal
    name: Main Bedroom Universal
    children:
      - media_player.main_bedroom
    commands:
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.tivoli_audio
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.tivoli_audio
    attributes:
      state: switch.tivoli_audio

automation:
  - alias: "Turn Audio On When Apple TV Turned On"
    id: "7c3646d2-8fe8-4378-a6f5-979e16cc40ff"
    initial_state: true
    trigger:
      platform: state
      entity_id: media_player.living_room
      from: standby
      # seems like an apple tv can turn on and be in a paused state immediately
      # to: idle
    mode: single
    action:
      - service: script.turn_on
        entity_id: script.hk_3380_power_on
      - delay: "00:00:10"
      - service: script.turn_on
        entity_id: script.samsung_tv_hdmi2
