# credit: https://github.com/tinuva/home-assistant-config/blob/8b16e0fa53be37682e4add2f338d8777bfd9896e/packages/energy/eskomsepush.yaml
# https://zatech.slack.com/archives/CG4HBE0NB/p1664122287331179?thread_ts=1664122287.331179&cid=CG4HBE0NB
# EskomSePush API Docs: https://documenter.getpostman.com/view/1296288/UzQuNk3E
# To sign up for a key, scroll down on their page for the API Request link: https://sepush.co.za/
# Direct link to sign-up form: https://docs.google.com/forms/d/e/1FAIpQLSeZhAkhDaQX_mLT2xn41TkVjLkOH3Py3YWHi_UqQP4niOY01g/viewform

# other interesting links:
# https://www.eskom.co.za/eskom-divisions/tx/system-adequacy-reports/

# calendars
# https://github.com/beyarkay/eskom-calendar/releases/download/latest/western-cape-stellenbosch.ics
# https://eskomcalendar.co.za/ec?calendar=eskom-direct-2-even.ics (also has an API)
#   - https://eskom-calendar-api.shuttleapp.rs/

# test stuff
# curl -s -X GET -H "Token: XXXXXXXX-XXXXXXXX-XXXXXXXX-XXXXXXXX" --url "https://developer.sepush.co.za/business/2.0/api_allowance"

# v3 api
# ðŸš¨ We have no plans to deprecate v2 right now. We might consider it if loadshedding starts again.
# https://zatech.slack.com/archives/C043YCM6BRS/p1764598351314599
# https://documenter.getpostman.com/view/1296288/2sB3dLVY6h

rest:
  # new: https://developer.sepush.co.za/business/3.0/schedule?id=eskme-2
  - resource: "https://developer.sepush.co.za/business/2.0/area"
    # maybe give this and the sensor below a scheduled update interval in future
    # https://community.home-assistant.io/t/rest-sensor-can-i-schedule-when-the-update-happens/408500
    scan_interval: 3600  # rate limit
    headers:
      token: !secret eskomsepush
    params:
      id: "eskme-2-stellenboschstellenboschwesterncape"
    sensor:
      - name: EskomSePush
        force_update: true
        value_template: "OK"
        json_attributes:
          - events
          - info
          - schedule

sensor:
  # Eskom se Push sensor
  - platform: rest
    name: EskomSePush Allowance
    # new: https://developer.sepush.co.za/business/3.0/api_allowance
    resource: "https://developer.sepush.co.za/business/2.0/api_allowance"
    headers:
      Token: !secret eskomsepush
    json_attributes_path: "$.allowance"
    json_attributes:
      - count
      - limit
      - type
    value_template: "OK"
    scan_interval: 3600

# template sensors abased on ESP above
template:
  - sensor:
      - name: "Loadshedding Start Time"
        unique_id: "7c572fed-f4e0-4889-83ea-8995932c1464"
        device_class: timestamp
        icon: mdi:clock-outline
        state: >-
          {% if states('sensor.eskomsepush')
                and not state_attr('sensor.eskomsepush', 'events') is none
                and state_attr('sensor.eskomsepush', 'events') != []
                and 'start' in (state_attr('sensor.eskomsepush', 'events') | first) %}
            {{ (state_attr('sensor.eskomsepush', 'events') | first).start }}
          {% else %}
            {{ 0 | as_datetime }}
          {% endif %}
  - sensor:
      - name: "Loadshedding End Time"
        unique_id: "c6e3c440-e930-434f-95fc-a9d68dd42fe4"
        device_class: timestamp
        icon: mdi:clock-outline
        state: >-
          {% if states('sensor.eskomsepush')
                and not state_attr('sensor.eskomsepush', 'events') is none
                and state_attr('sensor.eskomsepush', 'events') != []
                and 'end' in (state_attr('sensor.eskomsepush', 'events') | first) %}
            {{ (state_attr('sensor.eskomsepush', 'events') | first).end }}
          {% else %}
            {{ 0 | as_datetime }}
          {% endif %}
  - sensor:
      - name: "Loadshedding Stage"
        unique_id: "a7314ceb-7afa-4a71-ae9e-deb6b9d956d9"
        icon: >-
          {% if states('sensor.eskomsepush')
                and not state_attr('sensor.eskomsepush', 'events') is none
                and state_attr('sensor.eskomsepush', 'events') != []
                and 'note' in (state_attr('sensor.eskomsepush', 'events') | first) %}
            {% set stage = (state_attr('sensor.eskomsepush', 'events') | first).note %}
            {% if stage == 'Stage 1' %}
              mdi:gauge-empty
            {% elif stage == 'Stage 2' %}
              mdi:gauge-low
            {% elif stage == 'Stage 3' %}
              mdi:gauge
            {% else %}
              mdi:gauge-full
            {% endif %}
          {% else %}
            mdi:checkbox-marked-circle
          {% endif %}
        state: >-
          {% if states('sensor.eskomsepush')
                and not state_attr('sensor.eskomsepush', 'events') is none
                and state_attr('sensor.eskomsepush', 'events') != []
                and 'note' in (state_attr('sensor.eskomsepush', 'events') | first) %}
            {{ (state_attr('sensor.eskomsepush', 'events') | first).note }}
          {% else %}
            No loadshedding
          {% endif %}
  - sensor:
      - name: "Loadshedding Duration"
        unique_id: "03a725e4-77ce-4fbe-9a3e-5b15b064d14f"
        device_class: duration
        unit_of_measurement: h
        state: >-
          {%- if states('sensor.eskomsepush')
                 and not state_attr('sensor.eskomsepush', 'events') is none
                 and state_attr('sensor.eskomsepush', 'events') != [] -%}
            {{ (states('sensor.loadshedding_end_time') | as_datetime - states('sensor.loadshedding_start_time') | as_datetime).seconds/60/60 }}
          {%- else -%}
            {{ 0 }}
          {%- endif -%}
  - sensor:
      - name: "Eskomsepush Calls Remaining"
        unique_id: "c0a18142-5518-4274-b34d-4f7ab017a43d"
        icon: mdi:api
        state: "{{ state_attr('sensor.eskomsepush_allowance', 'limit') | int(0) - state_attr('sensor.eskomsepush_allowance', 'count') | int(0) }}"
  - sensor:
      - name: "Loadshedding Forecast"
        unique_id: "4ac805d7-5b15-400d-b3c7-402df2324ca5"
        state: >
          Your latest forecast:
          {% if state_attr('sensor.eskomsepush', 'events') != []
                and not state_attr('sensor.eskomsepush', 'events') is none -%}
            {#- to not exceed the 255 character limit of the sensor, limit this to the next 3 events -#}
            {%- set events = state_attr('sensor.eskomsepush', 'events')[0:3] -%}
            {%- for event in events %}
              {%- set date = as_timestamp(event['start']) | timestamp_custom('%a %d') -%}
              {%- set stage = event['note'] -%}
              {%- set start_time = as_timestamp(event['start']) | timestamp_custom('%H:%M') -%}
              {%- set end_time = as_timestamp(event['end']) | timestamp_custom('%H:%M') -%}
              {%- set duration = event['end'] | as_datetime - event['start'] | as_datetime -%}
              {%- set hours = duration.seconds // 3600 -%}
              {%- set minutes = (duration.seconds % 3600) // 60 %}
            - {{ date ~ ': ' ~ start_time ~ '-' ~ end_time ~ ' (' ~ '~' ~ hours ~ 'h; ' ~ stage ~ ')'}}
            {%- endfor -%}
          {%- else -%}
            No loadshedding.
          {%- endif -%}
  - binary_sensor:
      - name: "Loadshedding Active"
        unique_id: "9a79d7b4-1fb3-4892-8d21-4d93bfc67012"
        device_class: problem
        state: >-
          {%- if state_attr('sensor.eskomsepush', 'events') == []
                 or state_attr('sensor.eskomsepush', 'events') is none -%}
            False
          {%- else -%}
            {% set start = (state_attr('sensor.eskomsepush', 'events') | first).start | as_datetime %}
            {% set end = (state_attr('sensor.eskomsepush', 'events') | first).end | as_datetime %}
            {{ start <= now() <= end }}
          {%- endif -%}
  - binary_sensor:
      - name: "Loadshedding Scheduled"
        unique_id: "98af1b24-2aaf-460d-b519-7dc98658bbc3"
        device_class: problem
        state: >-
          {{ states('sensor.loadshedding_start_time') | as_datetime != 0 | as_datetime }}
          {# alternative; will be evaluated every minute; the above is likely more efficient #}
          {# {{ states('sensor.loadshedding_start_time') | as_datetime >= now() }} #}

timer:
  loadshedding_duration:
    name: Loadshedding Duration Remaining
    restore: true

automation:
  - alias: "Start Loadshedding Timer"
    id: "ed1036a6-3399-4e6b-a4ca-889e75da896f"
    trigger:
      - platform: time
        at: sensor.loadshedding_start_time
    mode: single
    condition:
      - condition: state
        entity_id: timer.loadshedding_duration
        state: "idle"
    action:
      - service: timer.start
        data:
          entity_id: timer.loadshedding_duration
          duration: >-
            {% set start = (state_attr('sensor.eskomsepush', 'events') | first).start | as_datetime %}
            {% set end = (state_attr('sensor.eskomsepush', 'events') | first).end | as_datetime %}
            {{ end - start }}

  - alias: "Loadshedding Forecast Notification"
    id: "89d2c61c-24b6-463a-8b2a-bfe07581e60e"
    trigger:
      - platform: state
        entity_id: sensor.loadshedding_forecast
        # this is a stopgap; don't know why sensor.loadshedding_forecast goes unavailable
        not_to:
          - "unavailable"
          - "unknown"
    mode: single
    # we truncate the forecast due to the length limit in home assistant, which then sometimes look like
    # nothing has changed, because the change is actually within the truncated part
    # we check here that the notification's text is actually different from the previous value
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
    action:
      - service: notify.family
        data:
          title: "âš¡ï¸ Loadshedding"
          message: "{{ states('sensor.loadshedding_forecast') }}"
          data:
            group: "home-electricity"
            url: homeassistant://navigate/lovelace/resources
            tag: "loadshedding-forecast-notification"

  - alias: "Upcoming Loadshedding Notification"
    id: "a7c1b125-56a1-48d3-bf54-4d5430c81508"
    initial_state: true
    trigger:
      - platform: template
        id: "60"
        value_template: >-
          {% set offset = 60 %}
          {% set t = (states('sensor.loadshedding_start_time') | as_datetime | as_local - timedelta(minutes=offset)).strftime('%Y-%d-%m %H:%M') %}
          {% set n = now().strftime('%Y-%d-%m %H:%M') %}
          {{ n == t }}
      # seems redundant now with a solar system
      # - platform: template
      #   id: "15"
      #   value_template: >-
      #     {% set offset = 15 %}
      #     {% set t = (states('sensor.loadshedding_start_time') | as_datetime | as_local - timedelta(minutes=offset)).strftime('%Y-%d-%m %H:%M') %}
      #     {% set n = now().strftime('%Y-%d-%m %H:%M') %}
      #     {{ n == t }}
    mode: single
    condition:
      - condition: time
        after: "05:00:00"
        before: "23:00:00"
    action:
      - service: notify.family
        data:
          title: "âš¡ï¸ Loadshedding"
          message: >-
            {% set start = (states('sensor.loadshedding_start_time') | as_datetime | as_local).strftime('%H:%M') %}
            {% set end = (states('sensor.loadshedding_end_time') | as_datetime | as_local).strftime('%H:%M') %}
            {% set duration = states('sensor.loadshedding_duration') | float(0) %}
            {% set hours = duration | int %}
            {% set minutes = duration - hours %}
            Starting in {{ trigger.id }} min: {{ start }}-{{ end }} (~{{ hours }}h; {{ states('sensor.loadshedding_stage') }}).
          data:
            group: "home-electricity"
            url: homeassistant://navigate/lovelace/resources
            tag: "upcoming-loadshedding-notification"

  - alias: "Clear Upcoming Loadshedding Notification"
    id: "a10bf510-d521-4b38-a771-c09b4325d4ff"
    trigger:
      - platform: time
        at: sensor.loadshedding_start_time
    mode: single
    action:
      - service: notify.family
        data:
          message: "clear_notification"
          data:
            tag: "upcoming-loadshedding-notification"
