timer:
  irrigation_front_lawn:
    name: "Front Lawn Irrigation Runtime"
    # duration: "00:05:00"
    restore: false
  irrigation_front_beds:
    name: "Front Beds Irrigation Runtime"
    restore: false
  irrigation_rear_lawn:
    name: "Rear Lawn Irrigation Runtime"
    restore: false
  irrigation_rear_beds:
    name: "Rear Beds Irrigation Runtime"
    restore: false
  irrigation_full_cycle_runtime:
    name: "Full Cycle Runtime"
    restore: false

input_datetime:
  irrigation_start_time:
    name: "Irrigation Start Time"
    has_date: false
    has_time: true

input_boolean:
  irrigation_monday:
    name: "Monday"
    icon: mdi:calendar
  irrigation_tuesday:
    name: "Tuesday"
    icon: mdi:calendar
  irrigation_wednesday:
    name: "Wednesday"
    icon: mdi:calendar
  irrigation_thursday:
    name: "Thursday"
    icon: mdi:calendar
  irrigation_friday:
    name: "Friday"
    icon: mdi:calendar
  irrigation_saturday:
    name: "Saturday"
    icon: mdi:calendar
  irrigation_sunday:
    name: "Sunday"
    icon: mdi:calendar

automation:
  - alias: "Start A Full Irrigation Cycle"
    id: "3e5ed8f9-9620-4890-b424-f85317d578e4"
    trigger:
      - platform: time
        at: input_datetime.irrigation_start_time
    condition: "{{ is_state('input_boolean.irrigation_' ~ now().strftime('%A') | lower, 'on') }}"
    action:
      # https://community.home-assistant.io/t/sprinkler-automation-with-esphome-a-complete-project/565077
      # https://www.reddit.com/r/Esphome/comments/12t5z8u/sprinkler_controller_and_esphome/?rdt=46144&onetap_auto=true
      - service: switch.turn_on
        target:
          entity_id: switch.irrigation_main

  - alias: "Notify When Irrigation Status Changed"
    id: "53f24f14-12a3-493a-a6d8-fcb4c552c236"
    trigger:
      - platform: state
        entity_id: switch.irrigation_main
        to:
          - "on"
          - "off"
        not_from: "unavailable"
    action:
      - service: notify.mobile_app_ceres
        data:
          # yard?
          title: "Garden"
          message: >-
            The irrigation has been turned {{ states('switch.irrigation_main') }}.
          data:
            group: "home-garden"
            url: homeassistant://navigate/lovelace/environment

  - alias: "Update Irrigation Full Cycle Runtime Timer"
    id: "df395613-0ba1-4245-a18b-e6bac386fa30"
    trigger:
      - platform: state
        entity_id: sensor.irrigation_main_run_duration
    action:
      if:
        - "{{ states('sensor.irrigation_main_run_duration') | int(0) > 0 }}"
      then:
        - service: timer.start
          target:
            entity_id: timer.irrigation_full_cycle_runtime
          data:
            duration: >-
              {{ states('sensor.irrigation_main_run_duration') | int(0) }}
      else:
        # check it timer is active?
        - service: timer.cancel
          target:
            entity_id: timer.irrigation_full_cycle_runtime

  - alias: "Update Irrigation Zone Timer"
    id: "a7ce8054-875f-4899-b093-a83274125e80"
    trigger:
      - platform: state
        entity_id:
          - switch.irrigation_front_lawn
          - switch.irrigation_front_beds
          - switch.irrigation_rear_lawn
          - switch.irrigation_rear_beds
    mode: parallel
    action:
      if:
        - "{{ is_state(trigger.entity_id, 'on') }}"
      then:
        - service: timer.start
          target:
            entity_id: "{{ trigger.entity_id | replace('switch', 'timer') }}"
          data:
            duration: >-
              {% set multiplier = states('number.irrigation_multiplier') | float(0) %}
              {% set duration_entity_id = trigger.entity_id | replace('switch', 'number') ~ "_run_duration" %}
              {% set duration = states(duration_entity_id) | int(0) %}
              {{ (duration * multiplier * 60) | round(0) }}
      else:
        # check it timer is active?
        - service: timer.cancel
          target:
            entity_id: "{{ trigger.entity_id | replace('switch', 'timer') }}"
