template:
  - binary_sensor:
      - name: "Grid Feed"
        device_class: power
        state: "{{ states('sensor.grid_frequency') | int(0) > 0 }}"
        icon: >-
          {% if states('sensor.grid_frequency') | int(0) > 0 %}
            mdi:transmission-tower
          {% else %}
            mdi:transmission-tower-off
          {% endif %}
  - sensor:
      - name: "Home Power"
        unique_id: "ec13fb72-1d08-427a-918b-e7549539a1be"
        unit_of_measurement: W
        device_class: power
        # battery power goes positive and negative (postive power means the battery is charging)
        state: "{{ states('sensor.grid_power') | int(0) + states('sensor.pv_power') | int(0) - states('sensor.battery_power') | int(0) }}"
      - name: "Home Power kW"
        unique_id: "0d70dd0f-a7e4-416b-a293-cb1d518bdfcf"
        unit_of_measurement: kW
        device_class: power
        state: "{{ ((states('sensor.home_power') | int(0)) / 1000) | round(3) }}"
      - name: "Solar Reserve"
        unique_id: "cdff01dd-8401-4c0e-a661-1a72d74dbb01"
        unit_of_measurement: W
        device_class: power
        state: >-
          {% set battery_threshold = 100 %}
          {% set pv_threshold = 10 %}
          {% set pv_potential = states('sensor.power_production_now') | int(0) %}
          {% set pv_power = states('sensor.pv_power_filtered') | int(0) %}
          {% set battery_power = states('sensor.battery_power_filtered') | int(0) %}
          {% if (pv_power > pv_potential and pv_power > pv_threshold) or (pv_power > pv_threshold and battery_power < -battery_threshold) %}
            0
          {% elif pv_potential > 0 %}
            {{ pv_potential - pv_power }}
          {% else %}
            0
          {% endif %}
      - name: "Solar Reserve kW"
        unique_id: "72bffd22-61c2-41f8-93d5-9dd79e60afc9"
        unit_of_measurement: kW
        device_class: power
        state: "{{ ((states('sensor.solar_reserve') | int(0)) / 1000) | round(3) }}"
      - name: "Solar Consumption Percentage"
        icon: mdi:solar-power
        unit_of_measurement: "%"
        state: >
          {% set battery_threshold = 100 %}
          {% set pv_threshold = 10 %}
          {% set pv_potential = states('sensor.power_production_now') | int(0) %}
          {% set pv_power = states('sensor.pv_power_filtered') | int(0) %}
          {% set battery_power = states('sensor.battery_power_filtered') | int(0) %}
          {% if (pv_power > pv_potential and pv_power > pv_threshold) or (pv_power > pv_threshold and battery_power < -battery_threshold) %}
            100
          {% elif pv_potential > 0 %}
            {{ (pv_power / pv_potential * 100) | round(0) }}
          {% else %}
            0
          {% endif %}
      - name: "Solar Reserve Percentage"
        icon: mdi:solar-power
        unit_of_measurement: "%"
        state: >
          {% if states('sensor.power_production_now') | int(0) > 0 %}
            {{ 100 - states('sensor.solar_consumption_percentage') | int(0) }}
          {% else %}
            0
          {% endif %}
      - name: "Battery Status"
        icon: >-
          {% set state = states('sensor.battery_state_of_charge') | int(0) %}
          {% set charging = "-charging" if states('sensor.battery_status') == "Charging" else "" %}
          {% set suffix = ((state + 5) // 10) * 10 %}
          {# empty #}
          {% if suffix <= 0 %}
            mdi:battery-alert-variant-outline
          {# full #}
          {% elif suffix == 100 %}
            {# choose the right full battery #}
            {% if charging != "" %}
              mdi:battery-charging-100
            {% else %}
              mdi:battery
            {% endif %}
          {# everything in between #}
          {% else %}
            mdi:battery{{ charging }}-{{ suffix }}
          {% endif %}
        state: >
          {%- set threshold = 100 -%}
          {%- set battery_power = states('sensor.battery_power_filtered') | int(0) -%}
          {%- if battery_power > threshold -%}
            Charging
          {%- elif battery_power < -threshold -%}
            Discharging
          {%- else -%}
            Trickling
          {%- endif %}
      - name: "Battery Time To Full"
        device_class: duration
        unit_of_measurement: s
        state: >
          {% set battery_status = states('sensor.battery_status') %}
          {% set rate = states('sensor.battery_change_of_charge') | float(0) | abs %}
          {% set current_charge = states('sensor.battery_state_of_charge') | float(0) %}
          {% if battery_status == 'Charging' %}
            {{ (100 - current_charge) * 60 * 60 / rate }}
          {% else %}
            0
          {% endif %}
      - name: "Battery Time To Empty"
        device_class: duration
        unit_of_measurement: s
        state: >
          {% set battery_status = states('sensor.battery_status') %}
          {% set rate = states('sensor.battery_change_of_charge') | float(0) | abs %}
          {% set current_charge = states('sensor.battery_state_of_charge') | float(0) %}
          {% if battery_status == 'Discharging' -%}
            {{ (current_charge - 20) * 60 * 60 / rate }}
          {% else %}
            0
          {% endif %}
      - name: "Solar Production Peak Today"
        state: "{{ (states('sensor.power_highest_peak_time_today') | as_datetime | as_local).strftime('%H:%m') }}"
      - name: "Solar Production Peak Tomorrow"
        state: "{{ (states('sensor.power_highest_peak_time_tomorrow') | as_datetime | as_local).strftime('%H:%m') }}"
      - name: "Solar Energy Utilisation Today"
        icon: mdi:solar-power-variant-outline
        unit_of_measurement: "%"
        state: >
          {% set consumption = states('sensor.daily_solar_energy_consumption') | float(0) %}
          {% set production = states('sensor.energy_production_today') | float(0) %}
          {{ min((consumption / production * 100) | int(0), 100) }}

sensor:
  - platform: derivative
    source: sensor.battery_state_of_charge
    name: "Battery Change of Charge"
    round: 1
    unit_time: h
    unit: "%/h"
    time_window: "00:05:00"
  # digital power meter in db
  - platform: integration
    name: "Total Electricity Consumption"
    source: sensor.current_power
    unit_prefix: k
    unit_time: h
    method: left
    round: 3
  - platform: integration
    name: "Home Energy"
    source: sensor.home_power
    unit_prefix: k
    unit_time: h
    method: left
    round: 3
  - platform: template
    sensors:
      monthly_grid_energy_consumption_forecast:
        unique_id: "5a0d7a1b-0bbd-42b0-9b21-5daf97eeade0"
        unit_of_measurement: "kWh"
        # alternative:
        # {{ ((now().replace(day=1) + timedelta(days=31)).replace(day=1) - timedelta(days=1)).day }}
        # from: https://community.home-assistant.io/t/calculate-estimated-monthly-kwh-value/558816/4
        value_template: >
          {% set now = now() %}
          {% set month = now.month %}
          {% set year = now.year %}
          {% set days = None %}
          {# feb: leap years #}
          {% if month == 2 and year is divisibleby 4 and not year is divisibleby 400 %}
            {% set days = 29 %}
          {# jan, mar, may, jul, aug, oct, dec #}
          {% elif month in [1,3,5,7,8,10,12] %}
            {% set days = 31 %}
          {# apr, jun, sep, nov #}
          {% elif month in [4,6,9,11] %}
            {% set days = 30 %}
          {# feb #}
          {% else %}
            {% set days = 28 %}
          {% endif %}
          {{ ((states('sensor.monthly_grid_energy_consumption') | int) / now.day * days) | round(3) }}
      monthly_home_energy_consumption_forecast:
        unique_id: "9a1c2a4e-76cd-416d-8680-fe1ea588f254"
        unit_of_measurement: "kWh"
        value_template: >
          {% set n = now() %}
          {% set days = ((n.replace(day=1) + timedelta(days=-31)).replace(day=1) - timedelta(days=1)).day %}
          {{ ((states('sensor.monthly_home_energy_consumption') | int) / n.day * days) | round(3) }}
  - platform: filter
    name: "PV Power Filtered"
    entity_id: sensor.pv_power
    filters:
      filter: lowpass
      time_constant: 10
      precision: 0
  - platform: filter
    name: "Battery Power Filtered"
    entity_id: sensor.battery_power
    filters:
      filter: lowpass
      time_constant: 10
      precision: 0

utility_meter:
  daily_grid_energy_consumption:
    unique_id: "cb11e11e-259d-43dc-bc65-a9752b0bd31a"
    source: sensor.grid_energy_in
    cycle: daily
  monthly_grid_energy_consumption:
    unique_id: "be9b3cac-80e0-4d59-8557-403d17100b22"
    source: sensor.grid_energy_in
    cycle: monthly
  daily_home_energy_consumption:
    unique_id: "765e119e-60ef-4e0b-87f0-e7d64adad81a"
    source: sensor.home_energy
    cycle: daily
  monthly_home_energy_consumption:
    unique_id: "ffcf90f5-5f22-47be-a389-8e74876ecead"
    source: sensor.home_energy
    cycle: monthly
  daily_solar_energy_consumption:
    unique_id: "c63e814c-4d6c-455c-bb2c-7f557a3af075"
    source: sensor.pv_energy
    cycle: daily

automation:
  - alias: "Notify If Grid Feed Status Changed"
    id: "b233b973-cf9b-44b5-94e4-5f0813e6eefa"
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.grid_feed
    action:
      - service: notify.mobile_app_ceres
        data:
          title: "Home"
          message: >-
            {% set after = "" %}
            {% set seconds = (as_timestamp(utcnow()) - as_timestamp(trigger.from_state.last_changed)) | int %}
            {% if seconds < 60 %}
              {% set after = seconds ~ " sec" %}
            {% elif seconds < 60*60 %}
              {% set after = seconds // 60 ~ " min" %}
            {% else %}
              {% set h = seconds // (60*60) %}
              {% set m = ((seconds / (60*60) - seconds // (60*60)) * 60) | round %}
              {% if m < 10 %}
                {% set after = h ~ "h0" ~ m %}
              {% else %}
                {% set after = h ~ "h" ~ m %}
              {% endif %}
            {% endif %}
            The grid feed has been {{ 'restored after ' ~  after ~ '.' if is_state('binary_sensor.grid_feed', 'on') else 'cut.' }}
          data:
            group: "home-electricity"
            url: homeassistant://navigate/lovelace/resources
  - alias: "Update Backup Power Warning Light If Grid Feed Status Changed"
    id: "e6ddb31c-3723-429d-a6c4-38268b831ba9"
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.grid_feed
    condition:
      - condition: state
        entity_id: binary_sensor.anybody_home
        state: "on"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.grid_feed
                state: "off"
              - condition: time
                after: "05:00:00"
                before: "23:00:00"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.foyer
                data:
                  profile: night
        default:
          - service: light.turn_off
            target:
              entity_id: light.foyer
  - alias: "Set Backup Power Warning Light Brightness"
    id: "09697150-0bf0-4dc7-9d6d-fbc5ac6cbdc7"
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.battery_state_of_charge
    condition:
      - condition: state
        entity_id: binary_sensor.grid_feed
        state: "off"
      - condition: state
        entity_id: binary_sensor.anybody_home
        state: "on"
    action:
      - service: light.turn_on
        target:
          entity_id: light.foyer
        data:
          profile: night
          # the function maps the state of charge range [100,30] of the battery to the brightness range [2,100] of the light
          # it's a linear function with a negative gradient
          brightness_pct: >-
            {% set state = states('sensor.battery_state_of_charge') | int(0) %}
            {# set state_bracketed = (state | int(0) + 5) // 10 * 10 #}
            {% set brightness = (-98/70*state + 142) | round(0) %}
            {{ min(brightness, 100) }}
