input_boolean:
  kitchen_smoke_detector_reminder:
    name: Kitchen Smoke Detector Reminder
    icon: mdi:reminder
  braai_room_smoke_detector_reminder:
    name: Braai Room Smoke Detector Reminder
    icon: mdi:reminder
  garage_smoke_detector_reminder:
    name: Garage Smoke Detector Reminder
    icon: mdi:reminder

shell_command:
  # https://community.home-assistant.io/t/shelly-plus-smoke-silence-alarm/747472
  mute_smoke_alarm: "curl -X POST -d '{\"id\": 1, \"method\": \"Smoke.Mute\", \"params\": {\"id\": 0}}' http://{{ host }}/rpc"

automation:
  - alias: "Alert When Water Detected"
    id: "c77aa289-96ab-4f80-b405-1f25a116f6c3"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.scullery_flooding
        to: "on"
    action:
      - service: notify.mobile_app_ceres
        data:
          title: "💧 Safety"
          message: >-
            {% set entity_id = trigger.entity_id %}
            {% set area = area_name(entity_id) | lower %}
            Water has been detected in the {{ area }}!
          data:
            group: "home-safety"
            url: homeassistant://navigate/lovelace-main/security
            push:
              sound:
                name: default
                critical: 1
                volume: 0.3

  - alias: "Alert When Smoke Detected"
    id: "3f2d5457-34db-464f-88d2-515fbb3e202a"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_smoke
          - binary_sensor.braai_room_smoke
          - binary_sensor.garage_smoke
        # https://www.home-assistant.io/integrations/binary_sensor/
        to: "on"
        id: "real"
      # https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Smoke/
      # curl -s -X GET http://<host>:<port>/api/webhook/kitchen_smoke_alarm_test
      - platform: webhook
        webhook_id: kitchen_smoke_alarm_test
        local_only: true
        # HTTP GET and HEAD requests are not enabled by default
        # https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger
        # why is this a GET? because shelly only supports a GET
        allowed_methods:
          - GET
        id: "test_kitchen_smoke"
      - platform: webhook
        webhook_id: braai_room_smoke_alarm_test
        local_only: true
        allowed_methods:
          - GET
        id: "test_braai_room_smoke"
      - platform: webhook
        webhook_id: garage_smoke_alarm_test
        local_only: true
        allowed_methods:
          - GET
        id: "test_garage_smoke"
    action:
      # clear the test notification
      # we do it this way instead of replacing the notification lower down, because we don't want to replace real notifications
      - if:
          - condition: template
            value_template: "{{ 'test' in trigger.id }}"
        then:
          - service: notify.mobile_app_ceres
            data:
              message: "clear_notification"
              data:
                tag: "{{ trigger.id | replace('test_', '') ~ '-test' }}"
      # we need to wait, otherwise it seems like the next notification will be cleared too
      # could be a race condition in HA, the companion app, ios or firebase – who knows...
      - delay:
          seconds: 1
      - service: notify.mobile_app_ceres
        data:
          title: "🔥 Safety"
          message: >-
            {% set prefix = '' %}
            {% set entity_id = '' %}
            {% if 'test' in trigger.id %}
              {% set prefix = '[Test]' %}
              {% set entity_id = trigger.id | replace('test_', 'binary_sensor.') %}
            {% else %}
              {% set entity_id = trigger.entity_id %}
            {% endif %}
            {% set area = area_name(entity_id) | lower %}
            {{ prefix }} Smoke has been detected in the {{ area }}!
          data:
            group: "home-safety"
            url: homeassistant://navigate/lovelace-main/security
            push:
              sound:
                name: default
                critical: 1
                volume: 0.3
            actions:
              - action: "GET_HELP"
                title: "Get help!"
                uri: "tel:+27218874777"
                destructive: true
            # todo: alert security company
            # request logged with olarm to see if they can provide an http request for a panic
            # for event automation:
            # - service: alarm_control_panel.alarm_trigger
            #   target:
            #     entity_id: alarm_control_panel.home
            # data:
            #   actions:
            #     - action: "ALERT_SECURITY_COMPANY"
            #       title: "Alert security company"
      - if:
          - "{{ 'test' in trigger.id }}"
        then:
          - service: input_boolean.turn_off
            target:
              entity_id: >-
                {% set reminder_entity = trigger.id | replace('test_', 'input_boolean.') ~ '_detector_reminder' %}
                {{ reminder_entity }}

  - alias: "Enable Smoke Detector Testing Reminders"
    id: "6e3c5bfb-6830-4aa4-b70c-bd53db3b51a6"
    trigger:
      - platform: time
        at: "01:00:00"
    condition:
      - condition: template
        value_template: "{{ now().day == 10 }}"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id:
            - input_boolean.kitchen_smoke_detector_reminder
            - input_boolean.braai_room_smoke_detector_reminder
            - input_boolean.garage_smoke_detector_reminder

  - alias: "Remind To Test Smoke Detectors"
    id: "07bcfd63-e5a3-44f1-9ff1-c8240e5f8ca6"
    variables:
      smoke_detectors:
        - binary_sensor.kitchen_smoke
        - binary_sensor.braai_room_smoke
        - binary_sensor.garage_smoke
    trigger:
      - platform: time
        at: "09:00:00"
    action:
      - repeat:
          for_each: "{{ smoke_detectors }}"
          sequence:
            - if:
                - condition: template
                  value_template: >-
                    {% set reminder_entity = repeat.item | replace('binary_sensor', 'input_boolean') ~ '_detector_reminder' %}
                    {{ is_state(reminder_entity,'on') }}
              then:
                - service: notify.mobile_app_ceres
                  data:
                    title: "✅ Safety Check"
                    message: >-
                      {% set area = area_name(repeat.item) | lower %}
                      Please test the {{ area }}'s smoke detector by pressing and holding the button for 3 sec.
                    data:
                      group: "home-safety"
                      tag: "{{ repeat.item | replace('binary_sensor.', '') ~ '-test' }}"
                      url: homeassistant://navigate/lovelace-main/security
