homeassistant:
  customize:
    switch.test_shelly1_relay:
      friendly_name: Shelly1 Test

input_boolean:
  test:
    name: Test
    icon: mdi:test-tube

input_number:
  test_percentage:
    min: 0
    max: 100
    unit_of_measurement: "%"

alert:
  test:
    name: Test Alert
    entity_id: input_boolean.test
    state: "on"
    repeat: 30  # min
    title: Test Title
    message: "Test message. {{ states('input_boolean.test') }}"
    data:
      group: "test-alerts"
      url: homeassistant://navigate/lovelace/devices
    notifiers:
      - mobile_app_ceres

script:
  test_foyer_light:
    fields:
      profile:
        description: "A light profile"
    sequence:
      - service: persistent_notification.create
        data:
          title: "Testing"
          message: "Test: '{{ profile }}'"
      - service: light.turn_on
        target:
          entity_id: light.foyer
        data:
          # entity_id: light.foyer
          profile: "{{ profile }}"

  test_nav:
    sequence:
      - service: notify.mobile_app_ceres
        data:
          title: "Test"
          message: "Navigate"
          data:
            url: homeassistant://navigate/lovelace/gallery

  test:
    description: "Test script"
    fields:
      param1:
        description: "Parameter 1"
        example: "Any text"
    sequence:
      - choose:
          - conditions:
              # duh
              # https://community.home-assistant.io/t/using-a-script-variable-field-in-a-choose-action/297289/2
              - condition: template
                value_template: "{{ param1 is not defined }}"
            sequence:
              - service: persistent_notification.create
                data:
                  title: "Testing"
                  message: "Test: no param"
        default:
          - service: persistent_notification.create
            data:
              title: "Testing"
              message: "Test: '{{ param1 }}'"

  test_snapshot:
    sequence:
      - service: camera.snapshot
        # https://github.com/home-assistant/core/issues/40241
        entity_id: camera.security_camera
        data:
          entity_id: camera.security_camera
          # https://community.home-assistant.io/t/referencing-entity-id-causing-a-template-error/236597
          # https://www.home-assistant.io/integrations/camera/#service-snapshot
          filename: '/tmp/snapshot_{{ entity_id.name }}.jpg'

  test_notification:
    sequence:
      - service: persistent_notification.create
        data:
          title: "Script Context Test"
          message: >-
            {% from 'util.jinja' import get_triggered_by_details %}
            {% set triggered_by = get_triggered_by_details(this.context) %}
            {{ triggered_by ~ '\n\n context: ' ~ (context.id, context.parent_id, context.user_id) ~ '\n\n this.context: ' ~ (this.context.id, this.context.parent_id, this.context.user_id) ~ '\n\n states.context: ' ~ (states.context.id, states.context.parent_id, states.context.user_id) }}

automation:
  - alias: "Battery Event Test"
    id: "af2a77e9-483f-4391-abe8-401c19c4baf0"
    initial_state: false
    trigger:
      - platform: event
        event_type: state_changed
    mode: single
    condition:
      - condition: template
        # https://www.home-assistant.io/docs/configuration/events/#state_changed
        value_template: "{{ trigger.event.data.entity_id in state_attr('sensor.monitored_batteries', 'batteries') }}"
    action:
      - service: system_log.write
        data:
          message: "{{ trigger.event }}"
          level: debug
          logger: "homeassistant.components.automation"
      # - service: notify.mobile_app_ceres
      #   data:
      #     title: "Batteries Test"
      #     message: "{{ trigger.event }}"
      #     data:
      #       group: "test"
      #       url: homeassistant://navigate/lovelace/devices
      - service: persistent_notification.create
        data:
          title: "Batteries Test"
          message: "{{ trigger.event }}"
      - service: automation.turn_off
        target:
          entity_id: "{{ this.entity_id }}"

  - alias: "Test Trigger Context"
    id: "a91edab1-0b60-40c1-89fa-cdf8a8112bd4"
    initial_state: false
    trigger:
      - platform: time_pattern
        seconds: "/1"
    action:
      - service: persistent_notification.create
        data:
          title: "Automation Context Test"
          # one can look at this under the automation trace, actually... (one needs a unique id for the automation)
          message: >-
            {% from 'util.jinja' import get_triggered_by_details %}
            {% set triggered_by = get_triggered_by_details(this.context) %}
            {{ triggered_by ~ '\n\n context: ' ~ (context.id, context.parent_id, context.user_id) ~ '\n\n this.context: ' ~ (this.context.id, this.context.parent_id, this.context.user_id) ~ '\n\n states.context: ' ~ (states.context.id, states.context.parent_id, states.context.user_id) }}
      - service: script.test_notification
      - service: automation.turn_off
        target:
          entity_id: "{{ this.entity_id }}"
