template:
  - binary_sensor:
      - name: "Workday Today"
        default_entity_id: binary_sensor.workday
        state: >
          {% set on_vacation = as_timestamp(states('input_datetime.vacation_start')) <= as_timestamp(now().date()) <= as_timestamp(states('input_datetime.vacation_end')) %}
          {{ is_state('binary_sensor.workday_sensor', 'on') and not on_vacation }}
  - binary_sensor:
      - name: "Workday Tomorrow"
        default_entity_id: binary_sensor.workday_tomorrow
        state: >
          {% set on_vacation_tomorrow = as_timestamp(states('input_datetime.vacation_start')) <= as_timestamp((now() + timedelta(days=1)).date()) <= as_timestamp(states('input_datetime.vacation_end')) %}
          {{ is_state('binary_sensor.workday_sensor_tomorrow', 'on') and not on_vacation_tomorrow }}

sensor:
  # https://community.home-assistant.io/t/prevent-zone-automation-from-triggering-when-briefly-entering-zone/360107/4
  - platform: history_stats
    name: Duration Pieter Work Cape Town
    entity_id: person.pieter_rautenbach
    state: "Work (Takealot HQ)"
    type: time  # duration
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Duration Pieter Work Stellenbosch
    entity_id: person.pieter_rautenbach
    state: "Work (Takealot STB)"
    type: time  # duration
    start: "{{ today_at() }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Duration Online Calls
    entity_id: binary_sensor.on_air
    state: "on"
    type: time  # duration
    start: "{{ today_at() }}"
    end: "{{ now() }}"
