input_boolean:
  gaia_audio_input_in_use_alt:
    name: Gaia Audio Input In Use (Alt)
    icon: mdi:microphone

binary_sensor:
  - platform: template
    sensors:
      workday:
        friendly_name: Workday Today
        value_template: >
          {% set on_vacation = as_timestamp(states('input_datetime.vacation_start')) <= as_timestamp(now().date()) <= as_timestamp(states('input_datetime.vacation_end')) %}
          {{ is_state('binary_sensor.workday_sensor', 'on') and not on_vacation }}
      workday_tomorrow:
        friendly_name: Workday Tomorrow
        value_template: >
          {% set on_vacation_tomorrow = as_timestamp(states('input_datetime.vacation_start')) <= as_timestamp((now() + timedelta(days=1)).date()) <= as_timestamp(states('input_datetime.vacation_end')) %}
          {{ is_state('binary_sensor.workday_sensor_tomorrow', 'on') and not on_vacation_tomorrow }}
      on_air:
        # https://github.com/home-assistant/iOS/issues/1903
        value_template: >
          {{ is_state('binary_sensor.gaia_audio_input_in_use', 'on') or
             is_state('input_boolean.gaia_audio_input_in_use_alt', 'on') }}

automation:
  - alias: "Change On Air Status"
    id: "0e9a98bc-dba8-4354-8bad-87b44b50703a"
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.on_air
    mode: single
    action:
      - service: "switch.turn_{{ 'on' if is_state('binary_sensor.on_air', 'on') else 'off' }}"
        entity_id: switch.on_air
  # alternative method due to this issue
  # https://github.com/home-assistant/iOS/issues/1903
  # source for detecting whether the mic is in use:
  # https://gist.github.com/ov1d1u/8e6ec1f0a087d1f410c65f16217273ba
  - alias: "Update Gaia Audio Input In Use (Alt)"
    id: "1f9cf72d-7e49-46fd-96c4-b422b6e923af"
    initial_state: true
    trigger:
      # curl -s -X PUT http://<host>:<port>/api/webhook/gaia_audio_input_in_use_alt -d 'status=<on/off>'
      - platform: webhook
        webhook_id: gaia_audio_input_in_use_alt
        allowed_methods:
          - PUT
        local_only: true
    mode: queued
    action:
      - service: "input_boolean.turn_{{ trigger.data.status }}"
        entity_id: input_boolean.gaia_audio_input_in_use_alt
